In [1]:
import numpy as np
import pandas as pd
from functools import reduce

In [2]:
all_subjects_sq00 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ00/Whole_Knee_Approach/moaks_fnih_sq00_all_info.csv',index_col=0)
new_names = [(i,i+'_00') for i in all_subjects_sq00.iloc[:, 2:].columns.values]
all_subjects_sq00.rename(columns = dict(new_names), inplace=True)
all_subjects_sq00

,ID,SIDE,XR_Osteophytes_00,FullTCL_00,AnyTCL_00,PartialTCL_00,BML_00,Meniscus_Degradation_00,Osteo_AND_FullTCL_00,Osteo_AND_PartialTCL_AND_BML_00,Osteo_AND_PartialTCL_AND_Meniscus_Degradation_00,Osteo_AND_BML_AND_Meniscus_Degradation_00,FullTCL_AND_BML_AND_Meniscus_Degradation_00,moaks_OA_00,V00XRKL_00
0,9001695,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0
1,9002116,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
2,9002430,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0
3,9002817,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
4,9003316,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,9993833,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
596,9994408,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
597,9995338,2,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0
598,9996098,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
599,9997381,1,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0

In [3]:
all_subjects_sq01 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ01/Whole_Knee_Approach/moaks_fnih_sq01_all_info.csv',index_col=0)
new_names = [(i,i+'_01') for i in all_subjects_sq01.iloc[:, 2:].columns.values]
all_subjects_sq01.rename(columns = dict(new_names), inplace=True)
all_subjects_sq01

,ID,SIDE,XR_Osteophytes_01,FullTCL_01,AnyTCL_01,PartialTCL_01,BML_01,Meniscus_Degradation_01,Osteo_AND_FullTCL_01,Osteo_AND_PartialTCL_AND_BML_01,Osteo_AND_PartialTCL_AND_Meniscus_Degradation_01,Osteo_AND_BML_AND_Meniscus_Degradation_01,FullTCL_AND_BML_AND_Meniscus_Degradation_01,moaks_OA_01,V01XRKL_01
0,9001695,1,1.0,NaN,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0
1,9002116,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
2,9002430,1,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
3,9002817,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
4,9003316,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,9993833,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
580,9994408,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
581,9995338,2,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
582,9996098,1,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0
583,9997381,1,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0

In [4]:
all_subjects_sq03 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ03/Whole_Knee_Approach/moaks_fnih_sq03_all_info.csv',index_col=0)
new_names = [(i,i+'_03') for i in all_subjects_sq03.iloc[:, 2:].columns.values]
all_subjects_sq03.rename(columns = dict(new_names), inplace=True)
all_subjects_sq03

,ID,SIDE,XR_Osteophytes_03,FullTCL_03,AnyTCL_03,PartialTCL_03,BML_03,Meniscus_Degradation_03,Osteo_AND_FullTCL_03,Osteo_AND_PartialTCL_AND_BML_03,Osteo_AND_PartialTCL_AND_Meniscus_Degradation_03,Osteo_AND_BML_AND_Meniscus_Degradation_03,FullTCL_AND_BML_AND_Meniscus_Degradation_03,moaks_OA_03,V03XRKL_03
0,9001695,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0
1,9002116,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,4.0
2,9002430,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0
3,9002817,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
4,9003316,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,9993833,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
596,9994408,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
597,9995338,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0
598,9996098,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0
599,9997381,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0

In [5]:
all_0001 = pd.merge(all_subjects_sq00,all_subjects_sq01,on=['ID','SIDE'],how='outer',indicator=True,suffixes=('_00','_01'))
cat_columns = all_0001.select_dtypes(['category']).columns
all_0001[cat_columns]=all_0001[cat_columns].apply(lambda x: x.cat.codes)
all_0001.rename(columns={'_merge': '_merge_0001'},inplace=True)
# print(all_0001['_merge_0001'].value_counts())
all_0001

,ID,SIDE,XR_Osteophytes_00,FullTCL_00,AnyTCL_00,PartialTCL_00,BML_00,Meniscus_Degradation_00,Osteo_AND_FullTCL_00,Osteo_AND_PartialTCL_AND_BML_00,...,BML_01,Meniscus_Degradation_01,Osteo_AND_FullTCL_01,Osteo_AND_PartialTCL_AND_BML_01,Osteo_AND_PartialTCL_AND_Meniscus_Degradation_01,Osteo_AND_BML_AND_Meniscus_Degradation_01,FullTCL_AND_BML_AND_Meniscus_Degradation_01,moaks_OA_01,V01XRKL_01,_merge_0001
0,9001695,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,2
1,9002116,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,2
2,9002430,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,2
3,9002817,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,2
4,9003316,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,9993833,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,2
596,9994408,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,2
597,9995338,2,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2
598,9996098,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,2
599,9997381,1,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,2

In [6]:
all_0103 = pd.merge(all_subjects_sq01,all_subjects_sq03,on=['ID','SIDE'],how='outer',indicator=True,suffixes=('_01','_03'))
cat_columns = all_0103.select_dtypes(['category']).columns
all_0103[cat_columns]=all_0103[cat_columns].apply(lambda x: x.cat.codes)
all_0103.rename(columns={'_merge': '_merge_0103'},inplace=True)
# print(all_0103['_merge_0103'].value_counts())
all_0103

,ID,SIDE,XR_Osteophytes_01,FullTCL_01,AnyTCL_01,PartialTCL_01,BML_01,Meniscus_Degradation_01,Osteo_AND_FullTCL_01,Osteo_AND_PartialTCL_AND_BML_01,...,BML_03,Meniscus_Degradation_03,Osteo_AND_FullTCL_03,Osteo_AND_PartialTCL_AND_BML_03,Osteo_AND_PartialTCL_AND_Meniscus_Degradation_03,Osteo_AND_BML_AND_Meniscus_Degradation_03,FullTCL_AND_BML_AND_Meniscus_Degradation_03,moaks_OA_03,V03XRKL_03,_merge_0103
0,9001695,1,1.0,NaN,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,2
1,9002116,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,4.0,2
2,9002430,1,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,2
3,9002817,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,2
4,9003316,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,9571631,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,1
596,9711687,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,1
597,9811840,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,2.0,1
598,9904574,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,1
599,9910719,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,1

In [7]:
all_0003 = pd.merge(all_subjects_sq00,all_subjects_sq03,on=['ID','SIDE'],how='outer',indicator=True,suffixes=('_00','_03'))
cat_columns = all_0003.select_dtypes(['category']).columns
all_0003[cat_columns]=all_0003[cat_columns].apply(lambda x: x.cat.codes)
all_0003.rename(columns={'_merge': '_merge_0003'},inplace=True)
# print(all_0003['_merge_0003'].value_counts())
all_0003

,ID,SIDE,XR_Osteophytes_00,FullTCL_00,AnyTCL_00,PartialTCL_00,BML_00,Meniscus_Degradation_00,Osteo_AND_FullTCL_00,Osteo_AND_PartialTCL_AND_BML_00,...,BML_03,Meniscus_Degradation_03,Osteo_AND_FullTCL_03,Osteo_AND_PartialTCL_AND_BML_03,Osteo_AND_PartialTCL_AND_Meniscus_Degradation_03,Osteo_AND_BML_AND_Meniscus_Degradation_03,FullTCL_AND_BML_AND_Meniscus_Degradation_03,moaks_OA_03,V03XRKL_03,_merge_0003
0,9001695,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,2
1,9002116,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,4.0,2
2,9002430,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,2
3,9002817,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,2
4,9003316,1,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,9993833,2,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,2
596,9994408,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,2
597,9995338,2,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,2
598,9996098,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,3.0,2
599,9997381,1,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,2.0,2

In [8]:
all_subjects_df = [all_subjects_sq00,all_subjects_sq01,all_subjects_sq03]
all_subjects_in_all_follow_ups =  reduce( lambda right, left: pd.merge(right,left,on = ['ID','SIDE'],how='outer',suffixes=('_0001','_0103')),all_subjects_df)
print(all_subjects_in_all_follow_ups.info())

print(all_subjects_in_all_follow_ups.isna().sum())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 600 entries, 0 to 599
Data columns (total 41 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   ID                                                600 non-null    int64
 1   SIDE                                              600 non-null    int64
 2   XR_Osteophytes_00                                 600 non-null    float64
 3   FullTCL_00                                        600 non-null    float64
 4   AnyTCL_00                                         600 non-null    float64
 5   PartialTCL_00                                     600 non-null    float64
 6   BML_00                                            599 non-null    float64
 7   Meniscus_Degradation_00                           600 non-null    float64
 8   Osteo_AND_FullTCL_00                              600 non-null    float64
 9   Osteo_AND_PartialTCL_AND_BML_00                   600 non-null    float64
 10  Osteo_AND_PartialTCL_AND_Meniscus_Degradation_00  600 non-null    float64
 11  Osteo_AND_BML_AND_Meniscus_Degradation_00         600 non-null    float64
 12  FullTCL_AND_BML_AND_Meniscus_Degradation_00       600 non-null    float64
 13  moaks_OA_00                                       600 non-null    float64
 14  V00XRKL_00                                        600 non-null    float64
 15  XR_Osteophytes_01                                 584 non-null    float64
 16  FullTCL_01                                        574 non-null    float64
 17  AnyTCL_01                                         579 non-null    float64
 18  PartialTCL_01                                     579 non-null    float64
 19  BML_01                                            542 non-null    float64
 20  Meniscus_Degradation_01                           579 non-null    float64
 21  Osteo_AND_FullTCL_01                              584 non-null    float64
 22  Osteo_AND_PartialTCL_AND_BML_01                   584 non-null    float64
 23  Osteo_AND_PartialTCL_AND_Meniscus_Degradation_01  584 non-null    float64
 24  Osteo_AND_BML_AND_Meniscus_Degradation_01         584 non-null    float64
 25  FullTCL_AND_BML_AND_Meniscus_Degradation_01       584 non-null    float64
 26  moaks_OA_01                                       584 non-null    float64
 27  V01XRKL_01                                        584 non-null    float64
 28  XR_Osteophytes_03                                 600 non-null    float64
 29  FullTCL_03                                        596 non-null    float64
 30  AnyTCL_03                                         600 non-null    float64
 31  PartialTCL_03                                     600 non-null    float64
 32  BML_03                                            569 non-null    float64
 33  Meniscus_Degradation_03                           600 non-null    float64
 34  Osteo_AND_FullTCL_03                              600 non-null    float64
 35  Osteo_AND_PartialTCL_AND_BML_03                   600 non-null    float64
 36  Osteo_AND_PartialTCL_AND_Meniscus_Degradation_03  600 non-null    float64
 37  Osteo_AND_BML_AND_Meniscus_Degradation_03         600 non-null    float64
 38  FullTCL_AND_BML_AND_Meniscus_Degradation_03       600 non-null    float64
 39  moaks_OA_03                                       600 non-null    float64
 40  V03XRKL_03                                        600 non-null    float64
dtypes: float64(39), int64(2)
memory usage: 196.9 KB
None
ID                                                   0
SIDE                                                 0
XR_Osteophytes_00                                    0
FullTCL_00                                           0
AnyTCL_00                                            0
PartialTCL_00                                        0
BML_00                                               1
Meniscus_Degradation_00                              0
Osteo_AND_FullTCL_00                                 0
Osteo_AND_PartialTCL_AND_BML_00                      0
Osteo_AND_PartialTCL_AND_Meniscus_Degradation_00     0
Osteo_AND_BML_AND_Meniscus_Degradation_00            0
FullTCL_AND_BML_AND_Meniscus_Degradation_00          0
moaks_OA_00                                          0
V00XRKL_00                                           0
XR_Osteophytes_01                                   16
FullTCL_01                                          26
AnyTCL_01                                           21
PartialTCL_01                                       21
BML_01                                              58
Meniscus_Degradation_01                             21
Osteo_AND_FullTCL_01                                16
Osteo_AND_PartialTCL_AND_BML_01                     16
Osteo_AND_PartialTCL_AND_Meniscus_Degradation_01    16
Osteo_AND_BML_AND_Meniscus_Degradation_01           16
FullTCL_AND_BML_AND_Meniscus_Degradation_01         16
moaks_OA_01                                         16
V01XRKL_01                                          16
XR_Osteophytes_03                                    0
FullTCL_03                                           4
AnyTCL_03                                            0
PartialTCL_03                                        0
BML_03                                              31
Meniscus_Degradation_03                              0
Osteo_AND_FullTCL_03                                 0
Osteo_AND_PartialTCL_AND_BML_03                      0
Osteo_AND_PartialTCL_AND_Meniscus_Degradation_03     0
Osteo_AND_BML_AND_Meniscus_Degradation_03            0
FullTCL_AND_BML_AND_Meniscus_Degradation_03          0
moaks_OA_03                                          0
V03XRKL_03                                           0
dtype: int64

In [9]:
all_subjects_in_all_follow_ups.to_csv('all_subjects_fnih_sq00_01_03.csv',index=False)

In [10]:

all_moaks_zero_sq00_01_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['moaks_OA_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['moaks_OA_01'] == 0.0) & (all_subjects_in_all_follow_ups['moaks_OA_03'] == 0.0),
                                ['ID','SIDE','moaks_OA_00','V00XRKL_00','moaks_OA_01','V01XRKL_01','moaks_OA_03','V03XRKL_03'])]
all_moaks_zero_sq00_01 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['moaks_OA_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['moaks_OA_01'] == 0.0),
                                ['ID','SIDE','moaks_OA_00','V00XRKL_00','moaks_OA_01','V01XRKL_01'])]

In [12]:
print('Number of subject that remained ZERO moaks in FNIH_SQ00 and FNIH_SQ01: {}'.format(len(all_moaks_zero_sq00_01)))
print('Number of subject that remained ZERO moaks in FNIH_SQ00 and FNIH_SQ01 and FNIH_SQ03: {}'.format(len(all_moaks_zero_sq00_01_03)))

Number of subject that remained ZERO moaks in FNIH_SQ00 and FNIH_SQ01: 101
Number of subject that remained ZERO moaks in FNIH_SQ00 and FNIH_SQ01 and FNIH_SQ03: 87

In [13]:
all_moaks_zero_sq00_01

          ID  SIDE  moaks_OA_00  V00XRKL_00  moaks_OA_01  V01XRKL_01
5    9003380     1          0.0         1.0          0.0         1.0
7    9004175     1          0.0         2.0          0.0         2.0
16   9015798     1          0.0         2.0          0.0         2.0
20   9021102     2          0.0         2.0          0.0         2.0
21   9022789     1          0.0         2.0          0.0         2.0
..       ...   ...          ...         ...          ...         ...
557  9917284     1          0.0         2.0          0.0         2.0
561  9925594     1          0.0         1.0          0.0         1.0
566  9936451     1          0.0         2.0          0.0         2.0
583  9969009     2          0.0         2.0          0.0         2.0
586  9981798     1          0.0         1.0          0.0         1.0

[101 rows x 6 columns]

In [14]:
all_moaks_zero_sq00_01_03

,ID,SIDE,moaks_OA_00,V00XRKL_00,moaks_OA_01,V01XRKL_01,moaks_OA_03,V03XRKL_03
5,9003380,1,0.0,1.0,0.0,1.0,0.0,1.0
7,9004175,1,0.0,2.0,0.0,2.0,0.0,2.0
16,9015798,1,0.0,2.0,0.0,2.0,0.0,2.0
20,9021102,2,0.0,2.0,0.0,2.0,0.0,2.0
21,9022789,1,0.0,2.0,0.0,2.0,0.0,2.0
...,...,...,...,...,...,...,...,...
543,9886575,1,0.0,1.0,0.0,1.0,0.0,1.0
548,9905156,1,0.0,2.0,0.0,2.0,0.0,2.0
549,9905276,1,0.0,1.0,0.0,1.0,0.0,1.0
555,9916496,1,0.0,1.0,0.0,1.0,0.0,1.0
583,9969009,2,0.0,2.0,0.0,2.0,0.0,2.0

In [15]:

all_moaks_zero_sq00_01.to_csv('moaks_fnih_sq00_01_that_remain_zero.csv',index=False)
all_moaks_zero_sq00_01_03.to_csv('moaks_fnih_sq00_01_03_that_remain_zero.csv',index=False)

In [16]:
all_moaks_one_sq00_01_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['moaks_OA_00'] == 1.0) &
                                (all_subjects_in_all_follow_ups['moaks_OA_01'] == 1.0) & (all_subjects_in_all_follow_ups['moaks_OA_03'] == 1.0),
                                ['ID','SIDE','moaks_OA_00','V00XRKL_00','moaks_OA_01','V01XRKL_01','moaks_OA_03','V03XRKL_03'])]
all_moaks_one_sq00_01 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['moaks_OA_00'] == 1.0) &
                                (all_subjects_in_all_follow_ups['moaks_OA_01'] == 1.0),
                                ['ID','SIDE','moaks_OA_00','V00XRKL_00','moaks_OA_01','V01XRKL_01'])]

In [17]:
print('Number of subject that remained ONE moaks in FNIH_SQ00 and FNIH_SQ01: {}'.format(len(all_moaks_one_sq00_01)))
print('Number of subject that remained ONE moaks in FNIH_SQ00 and FNIH_SQ01 and FNIH_SQ03: {}'.format(len(all_moaks_one_sq00_01_03)))

Number of subject that remained ONE moaks in FNIH_SQ00 and FNIH_SQ01: 446
Number of subject that remained ONE moaks in FNIH_SQ00 and FNIH_SQ01 and FNIH_SQ03: 442

In [18]:
all_moaks_one_sq00_01

          ID  SIDE  moaks_OA_00  V00XRKL_00  moaks_OA_01  V01XRKL_01
0    9001695     1          1.0         2.0          1.0         2.0
1    9002116     2          1.0         3.0          1.0         3.0
2    9002430     1          1.0         2.0          1.0         2.0
3    9002817     1          1.0         3.0          1.0         3.0
4    9003316     1          1.0         2.0          1.0         2.0
..       ...   ...          ...         ...          ...         ...
594  9993650     2          1.0         3.0          1.0         4.0
595  9993833     2          1.0         3.0          1.0         3.0
596  9994408     1          1.0         3.0          1.0         3.0
598  9996098     1          1.0         3.0          1.0         3.0
599  9997381     1          1.0         2.0          1.0         2.0

[446 rows x 6 columns]

In [19]:
all_moaks_one_sq00_01_03

,ID,SIDE,moaks_OA_00,V00XRKL_00,moaks_OA_01,V01XRKL_01,moaks_OA_03,V03XRKL_03
0,9001695,1,1.0,2.0,1.0,2.0,1.0,2.0
1,9002116,2,1.0,3.0,1.0,3.0,1.0,4.0
2,9002430,1,1.0,2.0,1.0,2.0,1.0,2.0
3,9002817,1,1.0,3.0,1.0,3.0,1.0,3.0
4,9003316,1,1.0,2.0,1.0,2.0,1.0,2.0
...,...,...,...,...,...,...,...,...
594,9993650,2,1.0,3.0,1.0,4.0,1.0,4.0
595,9993833,2,1.0,3.0,1.0,3.0,1.0,3.0
596,9994408,1,1.0,3.0,1.0,3.0,1.0,3.0
598,9996098,1,1.0,3.0,1.0,3.0,1.0,3.0
599,9997381,1,1.0,2.0,1.0,2.0,1.0,2.0

In [20]:
all_moaks_one_sq00_01.to_csv('moaks_fnih_sq00_01_that_remain_one.csv',index=False)
all_moaks_one_sq00_01_03.to_csv('moaks_fnih_sq00_01_03_that_remain_one.csv',index=False)

In [21]:
all_moaks_zero_sq00_01_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['moaks_OA_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['moaks_OA_01'] == 0.0) & (all_subjects_in_all_follow_ups['moaks_OA_03'] == 1.0),
                                ['ID','SIDE','moaks_OA_00','V00XRKL_00','moaks_OA_01','V01XRKL_01','moaks_OA_03','V03XRKL_03'])]
all_moaks_zero_sq00_one_01 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['moaks_OA_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['moaks_OA_01'] == 1.0),
                                ['ID','SIDE','moaks_OA_00','V00XRKL_00','moaks_OA_01','V01XRKL_01'])]

In [22]:
print('Number of subject with ZERO moaks in FNIH_SQ00 but ONE moaks in FNIH_SQ01: {}'.format(len(all_moaks_zero_sq00_one_01)))
print('Number of subject with ZERO moaks in FNIH_SQ00 and FNIH_SQ01 and one in FNIH_SQ03: {}'.format(len(all_moaks_zero_sq00_01_one_03)))

Number of subject with ZERO moaks in FNIH_SQ00 but ONE moaks in FNIH_SQ01: 20
Number of subject with ZERO moaks in FNIH_SQ00 and FNIH_SQ01 and one in FNIH_SQ03: 14

In [23]:
all_moaks_zero_sq00_one_01

          ID  SIDE  moaks_OA_00  V00XRKL_00  moaks_OA_01  V01XRKL_01
34   9049185     1          0.0         2.0          1.0         2.0
38   9054370     2          0.0         2.0          1.0         2.0
63   9089119     2          0.0         2.0          1.0         2.0
69   9098924     2          0.0         2.0          1.0         2.0
99   9154793     2          0.0         2.0          1.0         2.0
114  9184790     1          0.0         1.0          1.0         2.0
125  9212052     1          0.0         2.0          1.0         2.0
150  9255535     1          0.0         1.0          1.0         2.0
171  9291206     1          0.0         2.0          1.0         2.0
198  9332414     1          0.0         2.0          1.0         2.0
246  9409250     1          0.0         3.0          1.0         3.0
274  9435421     1          0.0         1.0          1.0         2.0
280  9445104     1          0.0         1.0          1.0         2.0
318  9480480     1          0.0         2.0          1.0         3.0
323  9486466     2          0.0         1.0          1.0         2.0
340  9502938     2          0.0         1.0          1.0         1.0
410  9602668     2          0.0         2.0          1.0         2.0
494  9762973     2          0.0         2.0          1.0         2.0
551  9907800     2          0.0         1.0          1.0         2.0
584  9976207     2          0.0         1.0          1.0         2.0

In [24]:
all_moaks_zero_sq00_01_one_03

,ID,SIDE,moaks_OA_00,V00XRKL_00,moaks_OA_01,V01XRKL_01,moaks_OA_03,V03XRKL_03
72,9101854,1,0.0,2.0,0.0,2.0,1.0,2.0
211,9357226,1,0.0,2.0,0.0,2.0,1.0,2.0
239,9396994,2,0.0,1.0,0.0,1.0,1.0,2.0
267,9423086,1,0.0,1.0,0.0,1.0,1.0,1.0
292,9457264,1,0.0,2.0,0.0,2.0,1.0,2.0
300,9465298,1,0.0,1.0,0.0,1.0,1.0,3.0
345,9510418,1,0.0,2.0,0.0,2.0,1.0,2.0
357,9534106,1,0.0,2.0,0.0,2.0,1.0,2.0
401,9590145,2,0.0,2.0,0.0,2.0,1.0,2.0
517,9817661,1,0.0,1.0,0.0,2.0,1.0,2.0
557,9917284,1,0.0,2.0,0.0,2.0,1.0,3.0
561,9925594,1,0.0,1.0,0.0,1.0,1.0,2.0
566,9936451,1,0.0,2.0,0.0,2.0,1.0,2.0
586,9981798,1,0.0,1.0,0.0,1.0,1.0,3.0

In [25]:
all_moaks_zero_sq00_one_01.to_csv('moaks_fnih_sq00_01_zero_sq00_one_sq01.csv',index=False)
all_moaks_zero_sq00_01_one_03.to_csv('moaks_fnih_sq00_01_03_zero_sq00_01_one_sq03.csv',index=False)

# NOW WE IDENTIFY THE INDIVIDUAL OA FEATURES THAT PROGRESSED BETWEEN THE TIME-POINTS OF THE STUDY

In [26]:
# NOW WE SAVE THE INCIDENT OA BASED ON EACH FEATURE SEPARATELY
all_moaks_BML_zero_sq00_one_01 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['BML_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['BML_01'] == 1.0),
                                ['ID','SIDE','BML_00','moaks_OA_00','V00XRKL_00','BML_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that progressed based on BML grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_BML_zero_sq00_one_01.shape[0]))
all_moaks_BML_zero_sq00_one_01.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_BML_zero00_one01.csv',index=False)

all_moaks_BML_zero_sq00_01_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['BML_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['BML_01'] == 0.0) & (all_subjects_in_all_follow_ups['BML_03'] == 1.0),
                                ['ID','SIDE','BML_00','moaks_OA_00','V00XRKL_00','BML_01','moaks_OA_01','V01XRKL_01',
                                'BML_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that progressed based on BML grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_BML_zero_sq00_01_one_03.shape[0]))                                
all_moaks_BML_zero_sq00_01_one_03.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_BML_zero0001_one03.csv',index=False)

Number of subjects that progressed based on BML grade between FNIH_SQ00 and FNIH_SQ01: 32
Number of subjects that progressed based on BML grade in every time step FNIH_SQ 00, 01 and 03: 35

In [27]:
all_moaks_Osteo_zero_sq00_one_01 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['XR_Osteophytes_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['XR_Osteophytes_01'] == 1.0),
                                ['ID','SIDE','XR_Osteophytes_00','moaks_OA_00','V00XRKL_00','XR_Osteophytes_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that progressed based on Osteo grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_Osteo_zero_sq00_one_01.shape[0]))
all_moaks_Osteo_zero_sq00_one_01.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_Osteo_zero00_one01.csv',index=False)

all_moaks_Osteo_zero_sq00_01_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['XR_Osteophytes_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['XR_Osteophytes_01'] == 0.0) & (all_subjects_in_all_follow_ups['XR_Osteophytes_03'] == 1.0),
                                ['ID','SIDE','XR_Osteophytes_00','moaks_OA_00','V00XRKL_00','XR_Osteophytes_01','moaks_OA_01','V01XRKL_01',
                                'XR_Osteophytes_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that progressed based on Osteo grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_Osteo_zero_sq00_01_one_03.shape[0]))                                
all_moaks_Osteo_zero_sq00_01_one_03.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_Osteo_zero0001_one03.csv',index=False)

Number of subjects that progressed based on Osteo grade between FNIH_SQ00 and FNIH_SQ01: 7
Number of subjects that progressed based on Osteo grade in every time step FNIH_SQ 00, 01 and 03: 7

In [28]:
all_moaks_FullTCL_zero_sq00_one_01 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['FullTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['FullTCL_01'] == 1.0),
                                ['ID','SIDE','FullTCL_00','moaks_OA_00','V00XRKL_00','FullTCL_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that progressed based on FullTCL grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_FullTCL_zero_sq00_one_01.shape[0]))
all_moaks_FullTCL_zero_sq00_one_01.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_FullTCL_zero00_one01.csv',index=False)

all_moaks_FullTCL_zero_sq00_01_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['FullTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['FullTCL_01'] == 0.0) & (all_subjects_in_all_follow_ups['FullTCL_03'] == 1.0),
                                ['ID','SIDE','FullTCL_00','moaks_OA_00','V00XRKL_00','FullTCL_01','moaks_OA_01','V01XRKL_01',
                                'FullTCL_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that progressed based on FullTCL grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_FullTCL_zero_sq00_01_one_03.shape[0]))                                
all_moaks_FullTCL_zero_sq00_01_one_03.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_FullTCL_zero0001_one03.csv',index=False)

Number of subjects that progressed based on FullTCL grade between FNIH_SQ00 and FNIH_SQ01: 4
Number of subjects that progressed based on FullTCL grade in every time step FNIH_SQ 00, 01 and 03: 17

In [29]:
all_moaks_PartialTCL_zero_sq00_one_01 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['PartialTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['PartialTCL_01'] == 1.0),
                                ['ID','SIDE','PartialTCL_00','moaks_OA_00','V00XRKL_00','PartialTCL_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that progressed based on PartialTCL grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_PartialTCL_zero_sq00_one_01.shape[0]))
all_moaks_PartialTCL_zero_sq00_one_01.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_PartialTCL_zero00_one01.csv',index=False)

all_moaks_PartialTCL_zero_sq00_01_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['PartialTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['PartialTCL_01'] == 0.0) & (all_subjects_in_all_follow_ups['PartialTCL_03'] == 1.0),
                                ['ID','SIDE','PartialTCL_00','moaks_OA_00','V00XRKL_00','PartialTCL_01','moaks_OA_01','V01XRKL_01',
                                'PartialTCL_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that progressed based on PartialTCL grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_PartialTCL_zero_sq00_01_one_03.shape[0]))                                
all_moaks_PartialTCL_zero_sq00_01_one_03.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_PartialTCL_zero0001_one03.csv',index=False)

Number of subjects that progressed based on PartialTCL grade between FNIH_SQ00 and FNIH_SQ01: 5
Number of subjects that progressed based on PartialTCL grade in every time step FNIH_SQ 00, 01 and 03: 5

In [30]:
all_moaks_AnyTCL_zero_sq00_one_01 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['AnyTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['AnyTCL_01'] == 1.0),
                                ['ID','SIDE','AnyTCL_00','moaks_OA_00','V00XRKL_00','AnyTCL_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that progressed based on AnyTCL grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_AnyTCL_zero_sq00_one_01.shape[0]))
all_moaks_AnyTCL_zero_sq00_one_01.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_AnyTCL_zero00_one01.csv',index=False)

all_moaks_AnyTCL_zero_sq00_01_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['AnyTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['AnyTCL_01'] == 0.0) & (all_subjects_in_all_follow_ups['AnyTCL_03'] == 1.0),
                                ['ID','SIDE','AnyTCL_00','moaks_OA_00','V00XRKL_00','AnyTCL_01','moaks_OA_01','V01XRKL_01',
                                'AnyTCL_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that progressed based on AnyTCL grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_AnyTCL_zero_sq00_01_one_03.shape[0]))                                
all_moaks_AnyTCL_zero_sq00_01_one_03.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_AnyTCL_zero0001_one03.csv',index=False)

Number of subjects that progressed based on AnyTCL grade between FNIH_SQ00 and FNIH_SQ01: 1
Number of subjects that progressed based on AnyTCL grade in every time step FNIH_SQ 00, 01 and 03: 5

In [31]:
all_moaks_Meniscus_zero_sq00_one_01 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['Meniscus_Degradation_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['Meniscus_Degradation_01'] == 1.0),
                                ['ID','SIDE','Meniscus_Degradation_00','moaks_OA_00','V00XRKL_00','Meniscus_Degradation_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that progressed based on Meniscus grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_Meniscus_zero_sq00_one_01.shape[0]))
all_moaks_Meniscus_zero_sq00_one_01.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_Meniscus_zero00_one01.csv',index=False)

all_moaks_Meniscus_zero_sq00_01_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['Meniscus_Degradation_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['Meniscus_Degradation_01'] == 0.0) & (all_subjects_in_all_follow_ups['Meniscus_Degradation_03'] == 1.0),
                                ['ID','SIDE','Meniscus_Degradation_00','moaks_OA_00','V00XRKL_00','Meniscus_Degradation_01','moaks_OA_01','V01XRKL_01',
                                'Meniscus_Degradation_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that progressed based on Meniscus grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_Meniscus_zero_sq00_01_one_03.shape[0]))                                
all_moaks_Meniscus_zero_sq00_01_one_03.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_Meniscus_zero0001_one03.csv',index=False)

Number of subjects that progressed based on Meniscus grade between FNIH_SQ00 and FNIH_SQ01: 8
Number of subjects that progressed based on Meniscus grade in every time step FNIH_SQ 00, 01 and 03: 8

# NOW WE FIND THOSE WHOSE FEATURES REMAINED THE SAME IN EACH TIME-STEP

In [32]:
# NOW WE SAVE THE INCIDENT OA BASED ON EACH FEATURE SEPARATELY
all_moaks_BML_zero_sq0001 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['BML_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['BML_01'] == 0.0),
                                ['ID','SIDE','BML_00','moaks_OA_00','V00XRKL_00','BML_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that stayed the same based on BML grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_BML_zero_sq0001.shape[0]))
all_moaks_BML_zero_sq0001.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_BML_zero0001.csv',index=False)

all_moaks_BML_zero_sq000103 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['BML_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['BML_01'] == 0.0) & (all_subjects_in_all_follow_ups['BML_03'] == 0.0),
                                ['ID','SIDE','BML_00','moaks_OA_00','V00XRKL_00','BML_01','moaks_OA_01','V01XRKL_01',
                                'BML_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that stayed the same based on BML grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_BML_zero_sq000103.shape[0]))                                
all_moaks_BML_zero_sq000103.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_BML_zero000103.csv',index=False)

Number of subjects that stayed the same based on BML grade between FNIH_SQ00 and FNIH_SQ01: 213
Number of subjects that stayed the same based on BML grade in every time step FNIH_SQ 00, 01 and 03: 178

In [33]:
all_moaks_Osteo_zero_sq0001 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['XR_Osteophytes_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['XR_Osteophytes_01'] == 0.0),
                                ['ID','SIDE','XR_Osteophytes_00','moaks_OA_00','V00XRKL_00','XR_Osteophytes_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that stayed the same based on Osteo grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_Osteo_zero_sq0001.shape[0]))
all_moaks_Osteo_zero_sq0001.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_Osteo_zero0001.csv',index=False)

all_moaks_Osteo_zero_sq000103 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['XR_Osteophytes_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['XR_Osteophytes_01'] == 0.0) & (all_subjects_in_all_follow_ups['XR_Osteophytes_03'] == 0.0),
                                ['ID','SIDE','XR_Osteophytes_00','moaks_OA_00','V00XRKL_00','XR_Osteophytes_01','moaks_OA_01','V01XRKL_01',
                                'XR_Osteophytes_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that stayed the same based on Osteo grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_Osteo_zero_sq000103.shape[0]))                                
all_moaks_Osteo_zero_sq000103.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_Osteo_zero000103.csv',index=False)

Number of subjects that stayed the same based on Osteo grade between FNIH_SQ00 and FNIH_SQ01: 46
Number of subjects that stayed the same based on Osteo grade in every time step FNIH_SQ 00, 01 and 03: 39

In [34]:
all_moaks_FullTCL_zero_sq0001 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['FullTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['FullTCL_01'] == 0.0),
                                ['ID','SIDE','FullTCL_00','moaks_OA_00','V00XRKL_00','FullTCL_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that stayed the same based on FullTCL grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_FullTCL_zero_sq0001.shape[0]))
all_moaks_FullTCL_zero_sq0001.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_FullTCL_zero0001.csv',index=False)

all_moaks_FullTCL_zero_sq000103 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['FullTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['FullTCL_01'] == 0.0) & (all_subjects_in_all_follow_ups['FullTCL_03'] == 0.0),
                                ['ID','SIDE','FullTCL_00','moaks_OA_00','V00XRKL_00','FullTCL_01','moaks_OA_01','V01XRKL_01',
                                'FullTCL_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that stayed the same based on FullTCL grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_FullTCL_zero_sq000103.shape[0]))                                
all_moaks_FullTCL_zero_sq000103.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_FullTCL_zero000103.csv',index=False)

Number of subjects that stayed the same based on FullTCL grade between FNIH_SQ00 and FNIH_SQ01: 504
Number of subjects that stayed the same based on FullTCL grade in every time step FNIH_SQ 00, 01 and 03: 483

In [35]:
all_moaks_PartialTCL_zero_sq0001 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['PartialTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['PartialTCL_01'] == 0.0),
                                ['ID','SIDE','PartialTCL_00','moaks_OA_00','V00XRKL_00','PartialTCL_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that stayed the same based on PartialTCL grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_PartialTCL_zero_sq0001.shape[0]))
all_moaks_PartialTCL_zero_sq0001.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_PartialTCL_zero0001.csv',index=False)

all_moaks_PartialTCL_zero_sq000103 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['PartialTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['PartialTCL_01'] == 0.0) & (all_subjects_in_all_follow_ups['PartialTCL_03'] == 0.0),
                                ['ID','SIDE','PartialTCL_00','moaks_OA_00','V00XRKL_00','PartialTCL_01','moaks_OA_01','V01XRKL_01',
                                'PartialTCL_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that stayed the same based on PartialTCL grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_PartialTCL_zero_sq000103.shape[0]))                                
all_moaks_PartialTCL_zero_sq000103.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_PartialTCL_zero000103.csv',index=False)

Number of subjects that stayed the same based on PartialTCL grade between FNIH_SQ00 and FNIH_SQ01: 91
Number of subjects that stayed the same based on PartialTCL grade in every time step FNIH_SQ 00, 01 and 03: 86

In [36]:
all_moaks_AnyTCL_zero_sq0001 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['AnyTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['AnyTCL_01'] == 0.0),
                                ['ID','SIDE','AnyTCL_00','moaks_OA_00','V00XRKL_00','AnyTCL_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that stayed the same based on AnyTCL grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_AnyTCL_zero_sq0001.shape[0]))
all_moaks_AnyTCL_zero_sq0001.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_AnyTCL_zero0001.csv',index=False)

all_moaks_AnyTCL_zero_sq000103 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['AnyTCL_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['AnyTCL_01'] == 0.0) & (all_subjects_in_all_follow_ups['AnyTCL_03'] == 0.0),
                                ['ID','SIDE','AnyTCL_00','moaks_OA_00','V00XRKL_00','AnyTCL_01','moaks_OA_01','V01XRKL_01',
                                'AnyTCL_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that stayed the same based on AnyTCL grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_AnyTCL_zero_sq000103.shape[0]))                                
all_moaks_AnyTCL_zero_sq000103.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_AnyTCL_zero000103.csv',index=False)

Number of subjects that stayed the same based on AnyTCL grade between FNIH_SQ00 and FNIH_SQ01: 29
Number of subjects that stayed the same based on AnyTCL grade in every time step FNIH_SQ 00, 01 and 03: 24

In [37]:
all_moaks_Meniscus_zero_sq0001 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['Meniscus_Degradation_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['Meniscus_Degradation_01'] == 0.0),
                                ['ID','SIDE','Meniscus_Degradation_00','moaks_OA_00','V00XRKL_00','Meniscus_Degradation_01','moaks_OA_01','V01XRKL_01'])]
print('Number of subjects that progressed based on Meniscus grade between FNIH_SQ00 and FNIH_SQ01: {}'.format(all_moaks_Meniscus_zero_sq0001.shape[0]))
all_moaks_Meniscus_zero_sq0001.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_Meniscus_zero0001.csv',index=False)

all_moaks_Meniscus_zero_sq000103 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups['Meniscus_Degradation_00'] == 0.0) &
                                (all_subjects_in_all_follow_ups['Meniscus_Degradation_01'] == 0.0) & (all_subjects_in_all_follow_ups['Meniscus_Degradation_03'] == 0.0),
                                ['ID','SIDE','Meniscus_Degradation_00','moaks_OA_00','V00XRKL_00','Meniscus_Degradation_01','moaks_OA_01','V01XRKL_01',
                                'Meniscus_Degradation_03','moaks_OA_03','V03XRKL_03'])]
print('Number of subjects that progressed based on Meniscus grade in every time step FNIH_SQ 00, 01 and 03: {}'.format(all_moaks_Meniscus_zero_sq000103.shape[0]))                                
all_moaks_Meniscus_zero_sq000103.to_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS_XR_OSTEO/MOAKS_FNIH_SQ_Compare/MOAKS_features_progression/moaks_fnih_sq00_01_03_Meniscus_zero000103.csv',index=False)

Number of subjects that progressed based on Meniscus grade between FNIH_SQ00 and FNIH_SQ01: 97
Number of subjects that progressed based on Meniscus grade in every time step FNIH_SQ 00, 01 and 03: 89