In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import classification_report

In [2]:
kxr_sq_bu01= pd.read_csv('/home/anastasis/EMC_Thesis/OAI Data/OAICompleteData_ASCII/kxr_sq_bu01.txt', sep="|")

In [3]:
kxr_sq_bu01

,ID,SIDE,readprj,VERSION,V01BARCDBU,V01XROSFM,V01XRSCFM,V01XRCYFM,V01XRJSM,V01XRCHM,...,V01XRKL,V01XROSFL,V01XRSCFL,V01XRCYFL,V01XRJSL,V01XRCHL,V01XROSTL,V01XRSCTL,V01XRCYTL,V01XRATTL
0,9000099,1,15,1.8,016601653203,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,9000099,2,15,1.8,016601653203,0.0,0.0,0.0,0.0,0.0,...,4.0,2.0,2.0,0.0,3.0,0.0,2.0,2.0,0.0,0.0
2,9000296,1,15,1.8,016601140204,0.0,0.0,0.0,1.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9000296,2,15,1.8,016601140204,0.0,1.0,0.0,2.0,0.0,...,3.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,9000622,1,15,1.8,016601597803,NaN,NaN,NaN,0.0,NaN,...,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8478,9999862,2,15,1.8,016601595304,0.0,0.0,0.0,1.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8479,9999865,1,15,1.8,016601436003,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
8480,9999865,2,15,1.8,016601436003,NaN,NaN,NaN,0.0,NaN,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
8481,9999878,1,15,1.8,016601317504,0.0,1.0,0.0,1.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8482,9999878,2,15,1.8,016601317504,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
KL_prj15 = kxr_sq_bu01[kxr_sq_bu01['readprj'] == 15].copy()
KL_prj15

,ID,SIDE,readprj,VERSION,V01BARCDBU,V01XROSFM,V01XRSCFM,V01XRCYFM,V01XRJSM,V01XRCHM,...,V01XRKL,V01XROSFL,V01XRSCFL,V01XRCYFL,V01XRJSL,V01XRCHL,V01XROSTL,V01XRSCTL,V01XRCYTL,V01XRATTL
0,9000099,1,15,1.8,016601653203,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,9000099,2,15,1.8,016601653203,0.0,0.0,0.0,0.0,0.0,...,4.0,2.0,2.0,0.0,3.0,0.0,2.0,2.0,0.0,0.0
2,9000296,1,15,1.8,016601140204,0.0,0.0,0.0,1.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9000296,2,15,1.8,016601140204,0.0,1.0,0.0,2.0,0.0,...,3.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,9000622,1,15,1.8,016601597803,NaN,NaN,NaN,0.0,NaN,...,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8478,9999862,2,15,1.8,016601595304,0.0,0.0,0.0,1.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8479,9999865,1,15,1.8,016601436003,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
8480,9999865,2,15,1.8,016601436003,NaN,NaN,NaN,0.0,NaN,...,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
8481,9999878,1,15,1.8,016601317504,0.0,1.0,0.0,1.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8482,9999878,2,15,1.8,016601317504,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
KL_prj15_osteophytes = KL_prj15.loc[:,['ID','SIDE','V01XROSFL','V01XROSFM','V01XROSTL','V01XROSTM','V01XRKL']]
KL_prj15_osteophytes

           ID  SIDE  V01XROSFL  V01XROSFM  V01XROSTL  V01XROSTM  V01XRKL
0     9000099     1        2.0        0.0        1.0        1.0      2.0
1     9000099     2        2.0        0.0        2.0        0.0      4.0
2     9000296     1        0.0        0.0        0.0        1.0      2.0
3     9000296     2        0.0        0.0        0.0        1.0      3.0
4     9000622     1        NaN        NaN        NaN        NaN      1.0
...       ...   ...        ...        ...        ...        ...      ...
8478  9999862     2        0.0        0.0        0.0        1.0      2.0
8479  9999865     1        NaN        NaN        NaN        NaN      0.0
8480  9999865     2        NaN        NaN        NaN        NaN      1.0
8481  9999878     1        0.0        0.0        0.0        1.0      2.0
8482  9999878     2        0.0        1.0        0.0        0.0      1.0

[8440 rows x 7 columns]

In [6]:
print(KL_prj15_osteophytes.V01XROSFM.value_counts())
print(KL_prj15_osteophytes.V01XROSFM.isna().sum())

0.0    2603
1.0    1150
3.0     841
2.0     538
Name: V01XROSFM, dtype: int64
3308

# FIRST WE LOAD THE FNIH STUDY

In [7]:
fnih_sq01 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS/MOAKS_FNIH_SQ01/Whole_Knee_Approach/moaks_fnih_sq01_initial_numeric_df.csv',index_col=0)
fnih_sq01

,ID,SIDE,VERSION,READPRJ,V01READER,V01MCMPM,V01MCMPL,V01MCMFMA,V01MCMFLA,V01MCMFMP,...,V01MGCSM,V01MGSST,V01MGCOTH,V01MANSBUR,V01MIPBUR,V01MPPBUR,V01MSYIC,V01MEFFWK,V01MITBSIG,V01MPOPCYS
0,9001695,1,1.1,22.0,2.0,0.5,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,NaN,1.0
1,9002116,2,1.1,22.0,2.0,2.0,0.0,2.0,1.0,2.1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,NaN,1.0
2,9002430,1,1.1,22.0,2.0,2.1,0.0,2.2,0.0,2.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0
3,9002817,1,1.1,22.0,2.0,2.0,1.0,0.0,0.0,2.0,...,0.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0,NaN,0.0
4,9003316,1,1.1,22.0,1.0,0.0,3.0,0.0,2.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,9993833,2,1.1,22.0,1.0,0.0,0.5,2.2,2.2,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,1.0
596,9994408,1,1.1,22.0,1.0,3.3,2.1,2.2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,NaN,0.0
597,9995338,2,1.1,22.0,1.0,0.0,2.2,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,1.0
598,9996098,1,1.1,22.0,1.0,3.2,3.0,2.2,2.2,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,NaN,0.0
599,9997381,1,1.1,22.0,1.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0

In [8]:
common_fnih_kxr_01 = pd.merge(fnih_sq01,KL_prj15_osteophytes,on=['ID','SIDE'],how='inner')
osteo_fnih_labels = ['ID','SIDE','V01MOSFMA','V01MOSFLA','V01MOSFMP','V01MOSFLP','V01MOSFMC','V01MOSFLC','V01MOSTM','V01MOSTL',
                    'V01XROSFL','V01XROSFM','V01XROSTL','V01XROSTM','V01XRKL']

common_fnih_kxr_01 = common_fnih_kxr_01.loc[:,osteo_fnih_labels]
common_fnih_kxr_01.fillna(0.0,inplace=True)
common_fnih_kxr_01

,ID,SIDE,V01MOSFMA,V01MOSFLA,V01MOSFMP,V01MOSFLP,V01MOSFMC,V01MOSFLC,V01MOSTM,V01MOSTL,V01XROSFL,V01XROSFM,V01XROSTL,V01XROSTM,V01XRKL
0,9001695,1,2.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0
1,9002116,2,2.0,2.0,3.0,2.0,2.0,2.0,2.0,0.0,1.0,2.0,1.0,2.0,3.0
2,9002430,1,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,0.0,1.0,2.0
3,9002817,1,1.0,1.0,2.0,0.0,2.0,2.0,2.0,1.0,0.0,3.0,1.0,1.0,3.0
4,9003316,1,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,9993833,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,3.0
580,9994408,1,1.0,1.0,1.0,0.0,2.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,3.0
581,9995338,2,1.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,2.0
582,9996098,1,1.0,0.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,3.0
583,9997381,1,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,2.0

In [9]:
common_fnih_kxr_01_NAN = common_fnih_kxr_01.loc[common_fnih_kxr_01.V01XROSFL.isna()]
print('Number of NaN values in combined Xray & MOAKS df is: {}'.format(common_fnih_kxr_01_NAN.shape[0]))

Number of NaN values in combined Xray & MOAKS df is: 0

# NOW WE CREATE THE CROSSTABLE FOR EACH REGION OF THE KNEE JOINT
# FOR THE MRI AND X-RAYS SCORES BETWEEN FNIH AND KL STUDIES

In [10]:
fnih_kxr_01_tm = pd.crosstab(common_fnih_kxr_01.V01MOSTM,common_fnih_kxr_01.V01XROSTM)
fnih_kxr_01_tm.to_csv('fnih_kxr_01_tm.csv')
fnih_kxr_01_tm_kappa = cohen_kappa_score(common_fnih_kxr_01.V01MOSTM,common_fnih_kxr_01.V01XROSTM)
print('Kappa coeff between TIBIAL MEDIAL XR Ostero and MOAKS Osteo grades: {}'.format(fnih_kxr_01_tm_kappa))
fnih_kxr_01_tm_class = classification_report(common_fnih_kxr_01.V01MOSTM,common_fnih_kxr_01.V01XROSTM)
print('Class Report between TIBIAL MEDIAL XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_tm_class))
fnih_kxr_01_tm_class = classification_report(common_fnih_kxr_01.V01MOSTM,common_fnih_kxr_01.V01XROSTM,output_dict=True)
fnih_kxr_01_tm_class_df = pd.DataFrame(fnih_kxr_01_tm_class).transpose()
fnih_kxr_01_tm_class_df.to_csv('fnih_kxr_01_tm_class.csv')

fnih_kxr_01_tl = pd.crosstab(common_fnih_kxr_01.V01MOSTL,common_fnih_kxr_01.V01XROSTL)
fnih_kxr_01_tl.to_csv('fnih_kxr_01_tl.csv')
fnih_kxr_01_tl_kappa = cohen_kappa_score(common_fnih_kxr_01.V01MOSTL,common_fnih_kxr_01.V01XROSTL)
print('Kappa coeff between TIBIAL LATERAL XR Ostero and MOAKS Osteo grades: {}'.format(fnih_kxr_01_tl_kappa))
fnih_kxr_01_tl_class = classification_report(common_fnih_kxr_01.V01MOSTL,common_fnih_kxr_01.V01XROSTL)
print('Class Report between TIBIAL LATERAL XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_tl_class))
fnih_kxr_01_tl_class = classification_report(common_fnih_kxr_01.V01MOSTL,common_fnih_kxr_01.V01XROSTL,output_dict=True)
fnih_kxr_01_tl_class_df = pd.DataFrame(fnih_kxr_01_tl_class).transpose()
fnih_kxr_01_tl_class_df.to_csv('fnih_kxr_01_tl_class.csv')

Kappa coeff between TIBIAL MEDIAL XR Ostero and MOAKS Osteo grades: 0.2768731813484333
Class Report between TIBIAL MEDIAL XR Ostero and MOAKS Osteo grades:
              precision    recall  f1-score   support

         0.0       0.69      0.43      0.53       196
         1.0       0.59      0.71      0.65       289
         2.0       0.34      0.31      0.33        89
         3.0       0.20      0.70      0.31        10

    accuracy                           0.55       584
   macro avg       0.46      0.54      0.45       584
weighted avg       0.58      0.55      0.55       584

Kappa coeff between TIBIAL LATERAL XR Ostero and MOAKS Osteo grades: 0.3926009753994557
Class Report between TIBIAL LATERAL XR Ostero and MOAKS Osteo grades:
              precision    recall  f1-score   support

         0.0       0.77      0.80      0.78       335
         1.0       0.59      0.56      0.57       200
         2.0       0.42      0.22      0.29        46
         3.0       0.12      1.00      0.22         3

    accuracy                           0.67       584
   macro avg       0.48      0.64      0.47       584
weighted avg       0.68      0.67      0.67       584

In [11]:
# fnih_kxr_01_fm_multi_index = pd.crosstab([common_fnih_kxr_01.V01MOSFMA,common_fnih_kxr_01.V01MOSFMC,common_fnih_kxr_01.V01MOSFMP]
#                             ,common_fnih_kxr_01.V01XROSFM)
# fnih_kxr_01_fm_multi_index.to_csv('fnih_kxr_01_fm_multi_index.csv')

fnih_kxr_01_fm_anterior = pd.crosstab(common_fnih_kxr_01.V01MOSFMA,common_fnih_kxr_01.V01XROSFM)
fnih_kxr_01_fm_anterior.to_csv('fnih_kxr_01_fm_anterior.csv')
# print(fnih_kxr_01_fm_anterior)
fnih_kxr_01_fm_anterior_kappa = cohen_kappa_score(common_fnih_kxr_01.V01MOSFMA,common_fnih_kxr_01.V01XROSFM)
# print('Femoral MEdial Osteophytes Anterior Kappa coeff is : {}'.format(fnih_kxr_01_fm_anterior_kappa))
fnih_kxr_01_fm_anterior_class = classification_report(common_fnih_kxr_01.V01MOSFMA,common_fnih_kxr_01.V01XROSFM)
# print('Class Report between FEMORAL MEDIAL ANTERIOR XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_fm_anterior_class))
fnih_kxr_01_fm_anterior_class = classification_report(common_fnih_kxr_01.V01MOSFMA,common_fnih_kxr_01.V01XROSFM,output_dict=True)
fnih_kxr_01_fm_anterior_class_df = pd.DataFrame(fnih_kxr_01_fm_anterior_class).transpose()
fnih_kxr_01_fm_anterior_class_df.to_csv('fnih_kxr_01_fm_class_anterior.csv')

fnih_kxr_01_fm_posterior = pd.crosstab(common_fnih_kxr_01.V01MOSFMP,common_fnih_kxr_01.V01XROSFM)
fnih_kxr_01_fm_posterior.to_csv('fnih_kxr_01_fm_posterior.csv')
# print(fnih_kxr_01_fm_posterior)
fnih_kxr_01_fm_posterior_kappa = cohen_kappa_score(common_fnih_kxr_01.V01MOSFMP,common_fnih_kxr_01.V01XROSFM)
print('Femoral MEdial Osteophytes posterior Kappa coeff is : {}'.format(fnih_kxr_01_fm_posterior_kappa))
fnih_kxr_01_fm_posterior_class = classification_report(common_fnih_kxr_01.V01MOSFMP,common_fnih_kxr_01.V01XROSFM)
# print('Class Report between FEMORAL MEDIAL POSTERIOR XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_fm_posterior_class))
fnih_kxr_01_fm_posterior_class = classification_report(common_fnih_kxr_01.V01MOSFMP,common_fnih_kxr_01.V01XROSFM,output_dict=True)
fnih_kxr_01_fm_posterior_class_df = pd.DataFrame(fnih_kxr_01_fm_posterior_class).transpose()
fnih_kxr_01_fm_posterior_class_df.to_csv('fnih_kxr_01_fm_class_posterior.csv')

fnih_kxr_01_fm_central = pd.crosstab(common_fnih_kxr_01.V01MOSFMC,common_fnih_kxr_01.V01XROSFM)
fnih_kxr_01_fm_central.to_csv('fnih_kxr_01_fm_central.csv')
# print(fnih_kxr_01_fm_central)
fnih_kxr_01_fm_central_kappa = cohen_kappa_score(common_fnih_kxr_01.V01MOSFMC,common_fnih_kxr_01.V01XROSFM)
print('Femoral MEdial Osteophytes central Kappa coeff is : {}'.format(fnih_kxr_01_fm_central_kappa))
fnih_kxr_01_fm_central_class = classification_report(common_fnih_kxr_01.V01MOSFMC,common_fnih_kxr_01.V01XROSFM)
# print('Class Report between FEMORAL MEDIAL central XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_fm_central_class))
fnih_kxr_01_fm_central_class = classification_report(common_fnih_kxr_01.V01MOSFMC,common_fnih_kxr_01.V01XROSFM,output_dict=True)
fnih_kxr_01_fm_central_class_df = pd.DataFrame(fnih_kxr_01_fm_central_class).transpose()
fnih_kxr_01_fm_central_class_df.to_csv('fnih_kxr_01_fm_class_central.csv')

fm_max_variables = common_fnih_kxr_01[['V01MOSFMA','V01MOSFMP','V01MOSFMC']].max(axis=1)
fnih_kxr_01_fm_max = pd.crosstab(fm_max_variables,common_fnih_kxr_01.V01XROSFM)
fnih_kxr_01_fm_max.to_csv('fnih_kxr_01_fm_max.csv')
# print(fnih_kxr_01_fm_max)
fnih_kxr_01_fm_max_kappa = cohen_kappa_score(fm_max_variables,common_fnih_kxr_01.V01XROSFM)
print('Femoral Medial Osteophytes (MAX VALUES) Kappa coeff is : {}'.format(fnih_kxr_01_fm_max_kappa))
fnih_kxr_01_fm_max_class = classification_report(fm_max_variables,common_fnih_kxr_01.V01XROSFM)
# print('Class Report between FEMORAL MEDIAL MAX XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_fm_max_class))
fnih_kxr_01_fm_max_class = classification_report(fm_max_variables,common_fnih_kxr_01.V01XROSFM,output_dict=True)
fnih_kxr_01_fm_max_class_df = pd.DataFrame(fnih_kxr_01_fm_max_class).transpose()
fnih_kxr_01_fm_max_class_df.to_csv('fnih_kxr_01_fm_class_max.csv')

Femoral MEdial Osteophytes posterior Kappa coeff is : 0.12469530252178707
Femoral MEdial Osteophytes central Kappa coeff is : 0.2958637005854544
Femoral Medial Osteophytes (MAX VALUES) Kappa coeff is : 0.2084171486044758

In [12]:
# fnih_kxr_01_fl_multi_index = pd.crosstab([common_fnih_kxr_01.V01MOSFLA,common_fnih_kxr_01.V01MOSFLC,common_fnih_kxr_01.V01MOSFLP]
#                             ,common_fnih_kxr_01.V01XROSFL)
# fnih_kxr_01_fl_multi_index.to_csv('fnih_kxr_01_fl_multi_index.csv')

fnih_kxr_01_fl_anterior = pd.crosstab(common_fnih_kxr_01.V01MOSFLA,common_fnih_kxr_01.V01XROSFL)
fnih_kxr_01_fl_anterior.to_csv('fnih_kxr_01_fl_anterior.csv')
# print(fnih_kxr_01_fl_anterior)
fnih_kxr_01_fl_anterior_kappa = cohen_kappa_score(common_fnih_kxr_01.V01MOSFLA,common_fnih_kxr_01.V01XROSFL)
# print('Femoral Lateral Osteophytes Anterior Kappa coeff is : {}'.format(fnih_kxr_01_fl_anterior_kappa))
fnih_kxr_01_fl_anterior_class = classification_report(common_fnih_kxr_01.V01MOSFLA,common_fnih_kxr_01.V01XROSFL)
# print('Class Report between FEMORAL Lateral ANTERIOR XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_fl_anterior_class))
fnih_kxr_01_fl_anterior_class = classification_report(common_fnih_kxr_01.V01MOSFLA,common_fnih_kxr_01.V01XROSFL,output_dict=True)
fnih_kxr_01_fl_anterior_class_df = pd.DataFrame(fnih_kxr_01_fl_anterior_class).transpose()
fnih_kxr_01_fl_anterior_class_df.to_csv('fnih_kxr_01_fl_class_anterior.csv')

fnih_kxr_01_fl_posterior = pd.crosstab(common_fnih_kxr_01.V01MOSFLP,common_fnih_kxr_01.V01XROSFL)
fnih_kxr_01_fl_posterior.to_csv('fnih_kxr_01_fl_posterior.csv')
# print(fnih_kxr_01_fl_posterior)
fnih_kxr_01_fl_posterior_kappa = cohen_kappa_score(common_fnih_kxr_01.V01MOSFLP,common_fnih_kxr_01.V01XROSFL)
# print('Femoral Lateral Osteophytes posterior Kappa coeff is : {}'.format(fnih_kxr_01_fl_posterior_kappa))
fnih_kxr_01_fl_posterior_class = classification_report(common_fnih_kxr_01.V01MOSFLP,common_fnih_kxr_01.V01XROSFL)
# print('Class Report between FEMORAL Lateral POSTERIOR XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_fl_posterior_class))
fnih_kxr_01_fl_posterior_class = classification_report(common_fnih_kxr_01.V01MOSFLP,common_fnih_kxr_01.V01XROSFL,output_dict=True)
fnih_kxr_01_fl_posterior_class_df = pd.DataFrame(fnih_kxr_01_fl_posterior_class).transpose()
fnih_kxr_01_fl_posterior_class_df.to_csv('fnih_kxr_01_fl_class_posterior.csv')

fnih_kxr_01_fl_central = pd.crosstab(common_fnih_kxr_01.V01MOSFLC,common_fnih_kxr_01.V01XROSFL)
fnih_kxr_01_fl_central.to_csv('fnih_kxr_01_fl_central.csv')
# print(fnih_kxr_01_fl_central)
fnih_kxr_01_fl_central_kappa = cohen_kappa_score(common_fnih_kxr_01.V01MOSFLC,common_fnih_kxr_01.V01XROSFL)
print('Femoral Lateral Osteophytes central Kappa coeff is : {}'.format(fnih_kxr_01_fl_central_kappa))
fnih_kxr_01_fl_central_class = classification_report(common_fnih_kxr_01.V01MOSFLC,common_fnih_kxr_01.V01XROSFL)
# print('Class Report between FEMORAL Lateral central XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_fl_central_class))
fnih_kxr_01_fl_central_class = classification_report(common_fnih_kxr_01.V01MOSFLC,common_fnih_kxr_01.V01XROSFL,output_dict=True)
fnih_kxr_01_fl_central_class_df = pd.DataFrame(fnih_kxr_01_fl_central_class).transpose()
fnih_kxr_01_fl_central_class_df.to_csv('fnih_kxr_01_fl_class_central.csv')

fl_max_variables = common_fnih_kxr_01[['V01MOSFLA','V01MOSFLP','V01MOSFLC']].max(axis=1)
fnih_kxr_01_fl_max = pd.crosstab(fl_max_variables,common_fnih_kxr_01.V01XROSFL)
fnih_kxr_01_fl_max.to_csv('fnih_kxr_01_fl_max.csv')
# print(fnih_kxr_01_fl_max)
fnih_kxr_01_fl_max_kappa = cohen_kappa_score(fl_max_variables,common_fnih_kxr_01.V01XROSFL)
print('Femoral Lateral Osteophytes (MAX VALUES) Kappa coeff is : {}'.format(fnih_kxr_01_fl_max_kappa))
fnih_kxr_01_fl_max_class = classification_report(fl_max_variables,common_fnih_kxr_01.V01XROSFL)
# print('Class Report between FEMORAL Lateral MAX XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_fl_max_class))
fnih_kxr_01_fl_max_class = classification_report(fl_max_variables,common_fnih_kxr_01.V01XROSFL,output_dict=True)
fnih_kxr_01_fl_max_class_df = pd.DataFrame(fnih_kxr_01_fl_max_class).transpose()
fnih_kxr_01_fl_max_class_df.to_csv('fnih_kxr_01_fl_class_max.csv')

Femoral Lateral Osteophytes central Kappa coeff is : 0.18571715862623728
Femoral Lateral Osteophytes (MAX VALUES) Kappa coeff is : 0.19498122226015713

# NOW WE CALCULATE METRICS REGARDING THE XR AND MRI OSTEOPHYTES GRADES USING TWO OA THRESHOLDS FOR XR

In [13]:
# XR OSTEO OA > = 2 
fnih_kxr_01_tm_xray2 = common_fnih_kxr_01.V01XROSTM
fnih_kxr_01_tm_xray2.loc[fnih_kxr_01_tm_xray2 < 1 ] = 0
fnih_kxr_01_tm_xray2.loc[fnih_kxr_01_tm_xray2 >=1 ] = 1
print('Osteo XR Tibial Medial >=2 value count is {}: '.format(fnih_kxr_01_tm_xray2.value_counts()))
fnih_kxr_01_tm_2 = common_fnih_kxr_01.V01MOSTM
fnih_kxr_01_tm_2.loc[fnih_kxr_01_tm_2 < 1] = 0
fnih_kxr_01_tm_2.loc[fnih_kxr_01_tm_2 >= 1] = 1
print('Osteo MR Tibial Medial >=2 value count is {}: '.format(fnih_kxr_01_tm_2.value_counts()))
fnih_kxr_01_tm_2_cross = pd.crosstab(fnih_kxr_01_tm_2,fnih_kxr_01_tm_xray2)
fnih_kxr_01_tm_2_cross.to_csv('fnih_kxr_01_tm_2.csv')
fnih_kxr_01_tm_2_kappa = cohen_kappa_score(fnih_kxr_01_tm_2,fnih_kxr_01_tm_xray2)
print('Osteo Tibial Medial >=2 Cohens Kappa Coeff is {}:'.format(fnih_kxr_01_tm_2_kappa))
fnih_kxr_01_tm_2_class = classification_report(fnih_kxr_01_tm_2,fnih_kxr_01_tm_xray2)
print('Class Report between TIBIA MEDIAL XR Ostero and MOAKS Osteo grades: \n:{}'.format(fnih_kxr_01_tm_2_class))
fnih_kxr_01_tm_2_class = classification_report(fnih_kxr_01_tm_2,fnih_kxr_01_tm_xray2,output_dict=True)
fnih_kxr_01_tm_2_class_df = pd.DataFrame(fnih_kxr_01_tm_2_class).transpose()
fnih_kxr_01_tm_2_class_df.to_csv('fnih_kxr_01_tm_2_class.csv')

fnih_kxr_01_tl_xray2 = common_fnih_kxr_01.V01XROSTL
fnih_kxr_01_tl_xray2.loc[fnih_kxr_01_tl_xray2 < 1 ] = 0
fnih_kxr_01_tl_xray2.loc[fnih_kxr_01_tl_xray2 >=1 ] = 1
print('Osteo XR Tibial Lateral >=2 value count is {}: '.format(fnih_kxr_01_tl_xray2.value_counts()))
fnih_kxr_01_tl_2 = common_fnih_kxr_01.V01MOSTL
fnih_kxr_01_tl_2.loc[fnih_kxr_01_tl_2 < 1] = 0
fnih_kxr_01_tl_2.loc[fnih_kxr_01_tl_2 >= 1] = 1
print('Osteo MR Tibial Lateral >=2 value count is {}: '.format(fnih_kxr_01_tl_2.value_counts()))
fnih_kxr_01_tl_2_cross = pd.crosstab(fnih_kxr_01_tl_2,fnih_kxr_01_tl_xray2)
fnih_kxr_01_tl_2_cross.to_csv('fnih_kxr_01_tl_2.csv')
fnih_kxr_01_tl_2_kappa = cohen_kappa_score(fnih_kxr_01_tl_2,fnih_kxr_01_tl_xray2)
print('Osteo Tibial Lateral >=2 Cohens Kappa Coeff is {}:'.format(fnih_kxr_01_tl_2_kappa))
fnih_kxr_01_tl_2_class = classification_report(fnih_kxr_01_tl_2,fnih_kxr_01_tl_xray2)
print('Class Report between TIBIA Lateral XR Ostero and MOAKS Osteo grades: \n:{}'.format(fnih_kxr_01_tl_2_class))
fnih_kxr_01_tl_2_class = classification_report(fnih_kxr_01_tl_2,fnih_kxr_01_tl_xray2,output_dict=True)
fnih_kxr_01_tl_2_class_df = pd.DataFrame(fnih_kxr_01_tl_2_class).transpose()
fnih_kxr_01_tl_2_class_df.to_csv('fnih_kxr_01_tl_2_class.csv')

fnih_kxr_01_fm_xray2 = common_fnih_kxr_01.V01XROSFM
fnih_kxr_01_fm_xray2.loc[fnih_kxr_01_fm_xray2 < 1 ] = 0
fnih_kxr_01_fm_xray2.loc[fnih_kxr_01_fm_xray2 >=1 ] = 1
print('Osteo XR Femoral Medial >=2 value count is {}: '.format(fnih_kxr_01_fm_xray2.value_counts()))
fnih_kxr_01_fm_max_2 = fm_max_variables
fnih_kxr_01_fm_max_2.loc[fnih_kxr_01_fm_max_2 < 1] = 0
fnih_kxr_01_fm_max_2.loc[fnih_kxr_01_fm_max_2 >= 1] = 1
print('Osteo MR Femoral Medial >=2 value count is {}: '.format(fnih_kxr_01_fm_max_2.value_counts()))
fnih_kxr_01_fm_max_2_cross = pd.crosstab(fnih_kxr_01_fm_max_2,fnih_kxr_01_fm_xray2)
fnih_kxr_01_fm_max_2_cross.to_csv('fnih_kxr_01_fm_max_2.csv')
fnih_kxr_01_fm_max_2_kappa = cohen_kappa_score(fnih_kxr_01_fm_max_2,fnih_kxr_01_fm_xray2)
print('Osteo Tibial Lateral >=2 Cohens Kappa Coeff is {}:'.format(fnih_kxr_01_fm_max_2_kappa))
fnih_kxr_01_fm_max_2_class = classification_report(fnih_kxr_01_fm_max_2,fnih_kxr_01_fm_xray2)
print('Class Report between TIBIA Lateral XR Ostero and MOAKS Osteo grades: \n:{}'.format(fnih_kxr_01_fm_max_2_class))
fnih_kxr_01_fm_max_2_class = classification_report(fnih_kxr_01_fm_max_2,fnih_kxr_01_fm_xray2,output_dict=True)
fnih_kxr_01_fm_max_2_class_df = pd.DataFrame(fnih_kxr_01_fm_max_2_class).transpose()
fnih_kxr_01_fm_max_2_class_df.to_csv('fnih_kxr_01_fm_max_2_class.csv')

fnih_kxr_01_fl_xray2 = common_fnih_kxr_01.V01XROSFL
fnih_kxr_01_fl_xray2.loc[fnih_kxr_01_fl_xray2 < 1 ] = 0
fnih_kxr_01_fl_xray2.loc[fnih_kxr_01_fl_xray2 >=1 ] = 1
print('Osteo XR Femoral Lateral >=2 value count is {}: '.format(fnih_kxr_01_fl_xray2.value_counts()))
fnih_kxr_01_fl_max_2 = fl_max_variables
fnih_kxr_01_fl_max_2.loc[fnih_kxr_01_fl_max_2 < 1] = 0
fnih_kxr_01_fl_max_2.loc[fnih_kxr_01_fl_max_2 >= 1] = 1
print('Osteo MR Femoral Lateral >=2 value count is {}: '.format(fnih_kxr_01_fl_max_2.value_counts()))
fnih_kxr_01_fl_max_2_cross = pd.crosstab(fnih_kxr_01_fl_max_2,fnih_kxr_01_fl_xray2)
fnih_kxr_01_fl_max_2_cross.to_csv('fnih_kxr_01_fl_max_2.csv')
fnih_kxr_01_fl_max_2_kappa = cohen_kappa_score(fnih_kxr_01_fl_max_2,fnih_kxr_01_fl_xray2)
print('Osteo Tibial Lateral >=2 Cohens Kappa Coeff is {}:'.format(fnih_kxr_01_fl_max_2_kappa))
fnih_kxr_01_fl_max_2_class = classification_report(fnih_kxr_01_fl_max_2,fnih_kxr_01_fl_xray2)
print('Class Report between TIBIA Lateral XR Ostero and MOAKS Osteo grades: \n:{}'.format(fnih_kxr_01_fl_max_2_class))
fnih_kxr_01_fl_max_2_class = classification_report(fnih_kxr_01_fl_max_2,fnih_kxr_01_fl_xray2,output_dict=True)
fnih_kxr_01_fl_max_2_class_df = pd.DataFrame(fnih_kxr_01_fl_max_2_class).transpose()
fnih_kxr_01_fl_max_2_class_df.to_csv('fnih_kxr_01_fl_max_2_class.csv')

Osteo XR Tibial Medial >=2 value count is 1.0    460
0.0    124
Name: V01XROSTM, dtype: int64:
Osteo MR Tibial Medial >=2 value count is 1.0    388
0.0    196
Name: V01MOSTM, dtype: int64:
Osteo Tibial Medial >=2 Cohens Kappa Coeff is 0.36646609581115475:
Class Report between TIBIA MEDIAL XR Ostero and MOAKS Osteo grades:
:              precision    recall  f1-score   support

         0.0       0.69      0.43      0.53       196
         1.0       0.76      0.90      0.82       388

    accuracy                           0.74       584
   macro avg       0.72      0.67      0.68       584
weighted avg       0.73      0.74      0.73       584

Osteo XR Tibial Lateral >=2 value count is 0.0    349
1.0    235
Name: V01XROSTL, dtype: int64:
Osteo MR Tibial Lateral >=2 value count is 0.0    335
1.0    249
Name: V01MOSTL, dtype: int64:
Osteo Tibial Lateral >=2 Cohens Kappa Coeff is 0.4710975329960272:
Class Report between TIBIA Lateral XR Ostero and MOAKS Osteo grades:
:              precision    recall  f1-score   support

         0.0       0.77      0.80      0.78       335
         1.0       0.71      0.67      0.69       249

    accuracy                           0.74       584
   macro avg       0.74      0.73      0.74       584
weighted avg       0.74      0.74      0.74       584

Osteo XR Femoral Medial >=2 value count is 1.0    364
0.0    220
Name: V01XROSFM, dtype: int64:
Osteo MR Femoral Medial >=2 value count is 1.0    522
0.0     62
dtype: int64:
Osteo Tibial Lateral >=2 Cohens Kappa Coeff is 0.16697717745691665:
Class Report between TIBIA Lateral XR Ostero and MOAKS Osteo grades:
:              precision    recall  f1-score   support

         0.0       0.20      0.69      0.30        62
         1.0       0.95      0.66      0.78       522

    accuracy                           0.66       584
   macro avg       0.57      0.68      0.54       584
weighted avg       0.87      0.66      0.73       584

Osteo XR Femoral Lateral >=2 value count is 0.0    336
1.0    248
Name: V01XROSFL, dtype: int64:
Osteo MR Femoral Lateral >=2 value count is 1.0    400
0.0    184
dtype: int64:
Osteo Tibial Lateral >=2 Cohens Kappa Coeff is 0.2928368290081763:
Class Report between TIBIA Lateral XR Ostero and MOAKS Osteo grades:
:              precision    recall  f1-score   support

         0.0       0.45      0.82      0.58       184
         1.0       0.87      0.54      0.66       400

    accuracy                           0.63       584
   macro avg       0.66      0.68      0.62       584
weighted avg       0.74      0.63      0.64       584

/home/anastasis/anaconda3/envs/tf/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/home/anastasis/anaconda3/envs/tf/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/home/anastasis/anaconda3/envs/tf/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/home/anastasis/anaconda3/envs/tf/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

# NOW WE CALCULATE THE KAPPA, ACCURACY, SENSITIVITY, SPECIFICITY FOR THE NEW THRESHOLD

In [14]:
fnih_kxr_01_tm_2_kappa = cohen_kappa_score(fnih_kxr_01_tm_2,fnih_kxr_01_tm_xray2)
print('Kappa coeff between TIBIAL MEDIAL XR Ostero and MOAKS Osteo grades: {}'.format(fnih_kxr_01_tm_2_kappa))
fnih_kxr_01_tm_2_class = classification_report(fnih_kxr_01_tm_2,fnih_kxr_01_tm_xray2)
print('Class Report between TIBIAL MEDIAL XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_tm_2_class))
fnih_kxr_01_tm_2_class = classification_report(fnih_kxr_01_tm_2,fnih_kxr_01_tm_xray2,output_dict=True)
fnih_kxr_01_tm_2_class_df = pd.DataFrame(fnih_kxr_01_tm_2_class).transpose()
fnih_kxr_01_tm_2_class_df.to_csv('fnih_kxr_01_tm_2_class.csv')

fnih_kxr_01_tl_2_kappa = cohen_kappa_score(fnih_kxr_01_tl_2,fnih_kxr_01_tl_xray2)
print('Kappa coeff between TIBIAL LATERAL XR Ostero and MOAKS Osteo grades: {}'.format(fnih_kxr_01_tl_2_kappa))
fnih_kxr_01_tl_2_class = classification_report(fnih_kxr_01_tl_2,fnih_kxr_01_tl_xray2)
print('Class Report between TIBIAL LATERAL XR Ostero and MOAKS Osteo grades: \n{}'.format(fnih_kxr_01_tl_2_class))
fnih_kxr_01_tl_2_class = classification_report(fnih_kxr_01_tl_2,fnih_kxr_01_tl_xray2,output_dict=True)
fnih_kxr_01_tl_2_class_df = pd.DataFrame(fnih_kxr_01_tl_2_class).transpose()
fnih_kxr_01_tl_2_class_df.to_csv('fnih_kxr_01_tl_2_class.csv')

Kappa coeff between TIBIAL MEDIAL XR Ostero and MOAKS Osteo grades: 0.36646609581115475
Class Report between TIBIAL MEDIAL XR Ostero and MOAKS Osteo grades:
              precision    recall  f1-score   support

         0.0       0.69      0.43      0.53       196
         1.0       0.76      0.90      0.82       388

    accuracy                           0.74       584
   macro avg       0.72      0.67      0.68       584
weighted avg       0.73      0.74      0.73       584

Kappa coeff between TIBIAL LATERAL XR Ostero and MOAKS Osteo grades: 0.4710975329960272
Class Report between TIBIAL LATERAL XR Ostero and MOAKS Osteo grades:
              precision    recall  f1-score   support

         0.0       0.77      0.80      0.78       335
         1.0       0.71      0.67      0.69       249

    accuracy                           0.74       584
   macro avg       0.74      0.73      0.74       584
weighted avg       0.74      0.74      0.74       584

# SECOND WE LOAD THE SQ STUDY

In [15]:
sq01 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/MOAKS/MOAKS_SQ01/Whole_Knee_Approach/moaks_sq01_initial_numeric_df.csv',index_col=0)
sq01

,ID,SIDE,READPRJ,VERSION,V01MCMPM,V01MCMPL,V01MCMFMA,V01MCMFLA,V01MCMFMP,V01MCMFLP,...,V01MGCSM,V01MGSST,V01MGCOTH,V01MANSBUR,V01MIPBUR,V01MPPBUR,V01MSYIC,V01MEFFWK,V01MPOPCYS,V01MITBSIG
0,9000798,2,65.0,1.2,2.0,0.0,2.0,2.0,2.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,2.0,3.0,-1.0,-1.0
1,9001400,1,65.0,1.2,2.0,2.0,2.0,2.0,0.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,-1.0,-1.0
2,9001897,2,65.0,1.2,2.0,2.0,3.0,2.0,0.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,0.0,-1.0,-1.0
6,9002316,2,65.0,1.2,2.0,3.0,0.0,0.0,0.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,2.0,1.0,-1.0,-1.0
7,9003316,2,65.0,1.2,0.0,2.0,2.0,1.0,0.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
957,9995338,1,65.0,1.2,1.0,2.0,0.0,1.0,0.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,1.0,-1.0,-1.0
958,9996865,1,65.0,1.2,2.0,3.0,2.0,3.0,2.0,2.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,2.0,2.0,-1.0,-1.0
959,9996865,2,65.0,1.2,3.0,3.0,2.0,3.0,2.0,2.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,2.0,1.0,-1.0,-1.0
960,9997869,2,65.0,1.2,0.0,0.0,1.0,0.0,0.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0
961,9999510,1,65.0,1.2,1.0,0.0,2.0,2.0,0.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,1.0,-1.0,-1.0

In [16]:
common_sq_kxr_01 = pd.merge(sq01,KL_prj15_osteophytes,on=['ID','SIDE'],how='inner')
osteo_sq_labels = ['ID','SIDE','V01MOSFMA','V01MOSFLA','V01MOSFMP','V01MOSFLP','V01MOSFMC','V01MOSFLC','V01MOSTM','V01MOSTL',
                    'V01XROSFL','V01XROSFM','V01XROSTL','V01XROSTM','V01XRKL']

common_sq_kxr_01 = common_sq_kxr_01.loc[:,osteo_fnih_labels]
common_sq_kxr_01

,ID,SIDE,V01MOSFMA,V01MOSFLA,V01MOSFMP,V01MOSFLP,V01MOSFMC,V01MOSFLC,V01MOSTM,V01MOSTL,V01XROSFL,V01XROSFM,V01XROSTL,V01XROSTM,V01XRKL
0,9000798,2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,3.0,3.0,3.0,4.0
1,9001400,1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,NaN,NaN,NaN,NaN,1.0
2,9001897,2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0
3,9002316,2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,1.0,2.0
4,9003316,2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911,9995338,1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0
912,9996865,1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,3.0,3.0,2.0,3.0,3.0
913,9996865,2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,3.0,3.0,1.0,3.0,4.0
914,9997869,2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0
915,9999510,1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,1.0,1.0

In [17]:
print(common_sq_kxr_01.V01XROSFL.isna().sum())
print(common_sq_kxr_01.V01XROSFM.isna().sum())
print(common_sq_kxr_01.V01XROSTL.isna().sum())
print(common_sq_kxr_01.V01XROSTM.isna().sum())

209
209
209
209

In [18]:
common_sq_kxr_01_NAN = common_sq_kxr_01.loc[common_sq_kxr_01.V01XROSFL.isna()]
common_sq_kxr_01_NAN.shape[0]

209

In [19]:
common_sq_kxr_01_zero = common_sq_kxr_01.loc[(common_sq_kxr_01.V01XROSFL == 0.0) & (common_sq_kxr_01.V01XROSFM == 0.0) &
                                                (common_sq_kxr_01.V01XROSTL == 0.0) & (common_sq_kxr_01.V01XROSTM == 0.0) & 
                                                (common_sq_kxr_01.V01XRKL >1)]
common_sq_kxr_01_zero = common_sq_kxr_01_zero.loc[:,['ID','SIDE','V01XROSFL','V01XROSFM','V01XROSTL','V01XROSTM','V01XRKL']]
common_sq_kxr_01_zero

          ID  SIDE  V01XROSFL  V01XROSFM  V01XROSTL  V01XROSTM  V01XRKL
71   9081635     1        0.0        0.0        0.0        0.0      2.0
505  9564280     2        0.0        0.0        0.0        0.0      2.0
864  9930342     1        0.0        0.0        0.0        0.0      4.0

# WE CREATE THE CROSSTABULAR TABLES JUST TO SEE HOW MANY KL GRADES THERE ARE
# SINCE SQ HAS NO MOAKS OSTEOPHYTES

In [20]:
sq_kxr_01_tm = pd.crosstab(common_sq_kxr_01.V01XROSTM,common_sq_kxr_01.V01MOSTM)
sq_kxr_01_tm.to_csv('sq_kxr_01_tm.csv')
sq_kxr_01_tl = pd.crosstab(common_sq_kxr_01.V01XROSTL,common_sq_kxr_01.V01MOSTL)
sq_kxr_01_tl.to_csv('sq_kxr_01_tl.csv')

sq_kxr_01_fm_multi_index = pd.crosstab([common_sq_kxr_01.V01MOSFMA,common_sq_kxr_01.V01MOSFMC,common_sq_kxr_01.V01MOSFMP]
                            ,common_sq_kxr_01.V01XROSFM)
sq_kxr_01_fm_multi_index.to_csv('sq_kxr_01_fm_multi_index.csv')
sq_kxr_01_fm_anterior = pd.crosstab(common_sq_kxr_01.V01MOSFMA,common_sq_kxr_01.V01XROSFM)
sq_kxr_01_fm_anterior.to_csv('sq_kxr_01_fm_anterior.csv')
# print(sq_kxr_01_fm_anterior)
sq_kxr_01_fm_posterior = pd.crosstab(common_sq_kxr_01.V01MOSFMP,common_sq_kxr_01.V01XROSFM)
sq_kxr_01_fm_posterior.to_csv('sq_kxr_01_fm_posterior.csv')
# print(sq_kxr_01_fm_posterior)
sq_kxr_01_fm_central = pd.crosstab(common_sq_kxr_01.V01MOSFMC,common_sq_kxr_01.V01XROSFM)
sq_kxr_01_fm_central.to_csv('sq_kxr_01_fm_central.csv')
# print(sq_kxr_01_fm_central)

sq_kxr_01_fl_multi_index = pd.crosstab([common_sq_kxr_01.V01MOSFLA,common_sq_kxr_01.V01MOSFLC,common_sq_kxr_01.V01MOSFLP]
                            ,common_sq_kxr_01.V01XROSFL)
sq_kxr_01_fl_multi_index.to_csv('sq_kxr_01_fl_multi_index.csv')
sq_kxr_01_fl_anterior = pd.crosstab(common_sq_kxr_01.V01MOSFLA,common_sq_kxr_01.V01XROSFL)
sq_kxr_01_fl_anterior.to_csv('sq_kxr_01_fl_anterior.csv')
# print(sq_kxr_01_fl_anterior)
sq_kxr_01_fl_posterior = pd.crosstab(common_sq_kxr_01.V01MOSFLP,common_sq_kxr_01.V01XROSFL)
sq_kxr_01_fl_posterior.to_csv('sq_kxr_01_fl_posterior.csv')
# print(sq_kxr_01_fl_posterior)
sq_kxr_01_fl_central = pd.crosstab(common_sq_kxr_01.V01MOSFLC,common_sq_kxr_01.V01XROSFL)
sq_kxr_01_fl_central.to_csv('sq_kxr_01_fl_central.csv')
print(sq_kxr_01_fl_central)

V01XROSFL  0.0  1.0  2.0  3.0
V01MOSFLC
-1.0       457  106   45   99