In [1]:
import numpy as np
import pandas as pd
from functools import reduce

In [2]:
all_subjects_sq00 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/WORMS/SQ_Link00/worms_sq00_all_info_thres1.csv',index_col=0)
new_names = [(i,i+'_00') for i in all_subjects_sq00.iloc[:, 2:].columns.values]
all_subjects_sq00.rename(columns = dict(new_names), inplace=True)
all_subjects_sq00

,ID,SIDE,Cartilage_Morphology_00,Partial_TCL_00,Full_TCL_00,BML_00,Meniscus_Degradation_00,VERSION_00,READPRJ_00,V00MWMTMA_00,...,V00MWBMFT_00,V00MWBMFM_00,V00MWBMFL_00,V00MWBMTM_00,V00MWBMTL_00,V00MWEFFWK_00,V00MWLB_00,V00MWPOPCY_00,_merge_without_sq_00,_merge_00
0,9003175,1,0.0,0.0,0.0,0.0,0.0,0.1,39,0,...,0,0,0,0,0,0.0,0.0,1.0,left_only,left_only
1,9011115,1,0.0,0.0,0.0,0.0,1.0,0.1,39,0,...,0,0,0,0,0,NaN,NaN,NaN,left_only,left_only
2,9011949,1,1.0,1.0,0.0,0.0,1.0,0.1,39,0,...,0,0,0,0,1,0.0,0.0,1.0,left_only,left_only
3,9013634,1,0.0,0.0,0.0,0.0,1.0,0.1,39,0,...,0,0,0,0,0,0.0,0.0,0.0,left_only,left_only
4,9020999,1,0.0,0.0,0.0,0.0,1.0,0.1,39,0,...,0,0,0,0,0,0.0,0.0,3.0,left_only,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,9973569,1,0.0,0.0,0.0,0.0,0.0,0.1,39,0,...,0,0,0,0,0,0.0,0.0,0.0,left_only,left_only
244,9979306,1,0.0,0.0,0.0,0.0,0.0,0.1,39,0,...,0,0,0,0,0,0.0,0.0,2.0,left_only,left_only
245,9982698,1,1.0,1.0,0.0,1.0,1.0,0.1,39,0,...,1,1,0,0,0,0.0,0.0,0.0,left_only,left_only
246,9989352,1,0.0,0.0,0.0,0.0,0.0,0.1,39,0,...,0,0,0,0,0,0.0,0.0,0.0,left_only,left_only
247,9995913,1,0.0,0.0,0.0,0.0,0.0,0.1,39,0,...,0,0,0,0,0,0.0,0.0,0.0,left_only,left_only

In [3]:
all_subjects_sq03 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/WORMS/SQ_Link03/worms_sq03_all_info_thres1.csv',index_col=0)
new_names = [(i,i+'_03') for i in all_subjects_sq03.iloc[:, 2:].columns.values]
all_subjects_sq03.rename(columns = dict(new_names), inplace=True)
all_subjects_sq03

,ID,SIDE,Cartilage_Morphology_03,Partial_TCL_03,Full_TCL_03,BML_03,Meniscus_Degradation_03,VERSION_03,READPRJ_03,V03MWMTMA_03,...,V03MWBMFT_03,V03MWBMFM_03,V03MWBMFL_03,V03MWBMTM_03,V03MWBMTL_03,V03MWEFFWK_03,V03MWLB_03,V03MWPOPCY_03,_merge_without_sq_03,_merge_03
0,9003175,1,0.0,0.0,0.0,0.0,0.0,3.1,39,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,left_only,left_only
1,9011115,1,0.0,0.0,0.0,0.0,1.0,3.1,39,0.0,...,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,left_only,left_only
2,9011949,1,1.0,1.0,0.0,1.0,1.0,3.1,39,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,left_only,left_only
3,9013634,1,0.0,0.0,0.0,0.0,1.0,3.1,39,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,left_only
4,9020999,1,0.0,0.0,0.0,0.0,1.0,3.1,39,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,left_only,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,9969009,1,0.0,0.0,0.0,0.0,0.0,3.1,39,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,left_only
242,9973569,1,0.0,0.0,0.0,0.0,0.0,3.1,39,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,left_only
243,9979306,1,0.0,0.0,0.0,0.0,0.0,3.1,39,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,left_only,left_only
244,9982698,1,1.0,1.0,0.0,0.0,1.0,3.1,39,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,left_only
245,9989352,1,0.0,0.0,0.0,0.0,0.0,3.1,39,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,left_only

In [4]:
all_subjects_sq06 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/WORMS/SQ_Link06/worms_sq06_all_info_thres1.csv',index_col=0)
new_names = [(i,i+'_06') for i in all_subjects_sq06.iloc[:, 2:].columns.values]
all_subjects_sq06.rename(columns = dict(new_names), inplace=True)
all_subjects_sq06

,ID,SIDE,Cartilage_Morphology_06,BML_06,Meniscus_Degradation_06,VERSION_06,READPRJ_06,V06MWMTMA_06,V06MWMTMB_06,V06MWMTMP_06,...,V06MWBMP_06,V06MWBMFT_06,V06MWBMFM_06,V06MWBMFL_06,V06MWBMTM_06,V06MWBMTL_06,V06MWEFFWK_06,V06MWLB_06,V06MWPOPCY_06,_merge_without_fnih_06
0,9003175,1,1.0,0.0,0.0,6.1,39,0,0,0,...,0,0,0,0,0,0,0.0,0.0,1.0,left_only
1,9011115,1,0.0,0.0,1.0,6.1,39,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,left_only
2,9011949,1,1.0,1.0,1.0,6.1,39,0,0,3,...,2,0,0,0,0,2,0.0,0.0,1.0,left_only
3,9013634,1,0.0,0.0,0.0,6.1,39,0,0,1,...,0,0,0,0,0,0,0.0,0.0,0.0,left_only
4,9015798,1,0.0,0.0,1.0,6.1,39,0,4,1,...,2,0,0,0,0,0,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,9973569,1,1.0,0.0,0.0,6.1,39,0,0,0,...,0,0,0,0,0,0,0.0,0.0,0.0,left_only
283,9979306,1,0.0,0.0,0.0,6.1,39,0,0,0,...,0,1,0,0,0,0,0.0,0.0,2.0,left_only
284,9982698,1,1.0,0.0,0.0,6.1,39,0,0,1,...,2,2,0,0,0,0,0.0,0.0,0.0,left_only
285,9989352,1,0.0,1.0,1.0,6.1,39,0,2,0,...,0,0,2,0,0,0,0.0,0.0,0.0,left_only
286,9995913,1,1.0,0.0,0.0,6.1,39,0,0,0,...,2,0,0,0,0,0,0.0,0.0,0.0,left_only

In [5]:
all_0003 = pd.merge(all_subjects_sq00,all_subjects_sq03,on=['ID','SIDE'],how='outer',indicator=True,suffixes=('_00','_03'))
cat_columns = all_0003.select_dtypes(['category']).columns
all_0003[cat_columns]=all_0003[cat_columns].apply(lambda x: x.cat.codes)
all_0003.rename(columns={'_merge': '_merge_0003'},inplace=True)
# print(all_0003['_merge_0003'].value_counts())
all_0003

,ID,SIDE,Cartilage_Morphology_00,Partial_TCL_00,Full_TCL_00,BML_00,Meniscus_Degradation_00,VERSION_00,READPRJ_00,V00MWMTMA_00,...,V03MWBMFM_03,V03MWBMFL_03,V03MWBMTM_03,V03MWBMTL_03,V03MWEFFWK_03,V03MWLB_03,V03MWPOPCY_03,_merge_without_sq_03,_merge_03,_merge_0003
0,9003175,1,0.0,0.0,0.0,0.0,0.0,0.1,39.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,left_only,left_only,2
1,9011115,1,0.0,0.0,0.0,0.0,1.0,0.1,39.0,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,left_only,left_only,2
2,9011949,1,1.0,1.0,0.0,0.0,1.0,0.1,39.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,2.0,left_only,left_only,2
3,9013634,1,0.0,0.0,0.0,0.0,1.0,0.1,39.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,left_only,2
4,9020999,1,0.0,0.0,0.0,0.0,1.0,0.1,39.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,left_only,left_only,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,9551668,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,left_only,left_only,1
250,9564189,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,left_only,1
251,9572192,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,left_only,left_only,1
252,9764936,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,left_only,left_only,1
253,9967294,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,left_only,left_only,1

In [6]:
all_0006 = pd.merge(all_subjects_sq00,all_subjects_sq06,on=['ID','SIDE'],how='outer',indicator=True,suffixes=('_00','_06'))
cat_columns = all_0006.select_dtypes(['category']).columns
all_0006[cat_columns]=all_0006[cat_columns].apply(lambda x: x.cat.codes)
all_0006.rename(columns={'_merge': '_merge_0006'},inplace=True)
# print(all_0006['_merge_0006'].value_counts())
all_0006

,ID,SIDE,Cartilage_Morphology_00,Partial_TCL_00,Full_TCL_00,BML_00,Meniscus_Degradation_00,VERSION_00,READPRJ_00,V00MWMTMA_00,...,V06MWBMFT_06,V06MWBMFM_06,V06MWBMFL_06,V06MWBMTM_06,V06MWBMTL_06,V06MWEFFWK_06,V06MWLB_06,V06MWPOPCY_06,_merge_without_fnih_06,_merge_0006
0,9003175,1,0.0,0.0,0.0,0.0,0.0,0.1,39.0,0.0,...,0,0,0,0,0,0.0,0.0,1.0,left_only,2
1,9011115,1,0.0,0.0,0.0,0.0,1.0,0.1,39.0,0.0,...,0,0,0,0,0,NaN,NaN,NaN,left_only,2
2,9011949,1,1.0,1.0,0.0,0.0,1.0,0.1,39.0,0.0,...,0,0,0,0,2,0.0,0.0,1.0,left_only,2
3,9013634,1,0.0,0.0,0.0,0.0,1.0,0.1,39.0,0.0,...,0,0,0,0,0,0.0,0.0,0.0,left_only,2
4,9020999,1,0.0,0.0,0.0,0.0,1.0,0.1,39.0,0.0,...,0,0,0,0,0,0.0,0.0,3.0,left_only,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,9793882,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0.0,0.0,0.0,left_only,1
283,9805931,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,0,0,0,0.0,0.0,0.0,left_only,1
284,9820271,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,3,0,2,0,0.0,0.0,1.0,left_only,1
285,9838317,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0.0,0.0,0.0,left_only,1
286,9886575,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,2,0,0,0.0,0.0,0.0,left_only,1

In [7]:
all_0306 = pd.merge(all_subjects_sq03,all_subjects_sq06,on=['ID','SIDE'],how='outer',indicator=True,suffixes=('_03','_06'))
cat_columns = all_0306.select_dtypes(['category']).columns
all_0306[cat_columns]=all_0306[cat_columns].apply(lambda x: x.cat.codes)
all_0306.rename(columns={'_merge': '_merge_0306'},inplace=True)
# print(all_0306['_merge_0306'].value_counts())
all_0306

,ID,SIDE,Cartilage_Morphology_03,Partial_TCL_03,Full_TCL_03,BML_03,Meniscus_Degradation_03,VERSION_03,READPRJ_03,V03MWMTMA_03,...,V06MWBMFT_06,V06MWBMFM_06,V06MWBMFL_06,V06MWBMTM_06,V06MWBMTL_06,V06MWEFFWK_06,V06MWLB_06,V06MWPOPCY_06,_merge_without_fnih_06,_merge_0306
0,9003175,1,0.0,0.0,0.0,0.0,0.0,3.1,39.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,left_only,2
1,9011115,1,0.0,0.0,0.0,0.0,1.0,3.1,39.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,left_only,2
2,9011949,1,1.0,1.0,0.0,1.0,1.0,3.1,39.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,left_only,2
3,9013634,1,0.0,0.0,0.0,0.0,1.0,3.1,39.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,2
4,9020999,1,0.0,0.0,0.0,0.0,1.0,3.1,39.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,left_only,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,9838317,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,1
284,9877790,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,1
285,9886575,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,left_only,1
286,9891187,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,1
287,9995913,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,left_only,1

In [8]:
all_subjects_df = [all_subjects_sq00,all_subjects_sq03,all_subjects_sq06]
all_subjects_in_all_follow_ups =  pd.DataFrame(reduce(lambda right, left: pd.merge(right,left,on = ['ID','SIDE'],how='outer'),all_subjects_df))
print(all_subjects_in_all_follow_ups.info())
print(all_subjects_in_all_follow_ups.columns.to_list())
# print(all_subjects_in_all_follow_ups.isna().sum())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 288 entries, 0 to 287
Columns: 113 entries, ID to _merge_without_fnih_06
dtypes: float64(106), int64(2), object(5)
memory usage: 256.5+ KB
None
['ID', 'SIDE', 'Cartilage_Morphology_00', 'Partial_TCL_00', 'Full_TCL_00', 'BML_00', 'Meniscus_Degradation_00', 'VERSION_00', 'READPRJ_00', 'V00MWMTMA_00', 'V00MWMTMB_00', 'V00MWMTMP_00', 'V00MWMTLA_00', 'V00MWMTLB_00', 'V00MWMTLP_00', 'V00MWMTMS_00', 'V00MWMTLS_00', 'V00MWACL_00', 'V00MWPCL_00', 'V00MWMCL_00', 'V00MWLCL_00', 'V00MWPATND_00', 'V00MWPOTND_00', 'V00MWCMP_00', 'V00MWCMFT_00', 'V00MWCMFM_00', 'V00MWCMFL_00', 'V00MWCMTM_00', 'V00MWCMTL_00', 'V00MWBMP_00', 'V00MWBMFT_00', 'V00MWBMFM_00', 'V00MWBMFL_00', 'V00MWBMTM_00', 'V00MWBMTL_00', 'V00MWEFFWK_00', 'V00MWLB_00', 'V00MWPOPCY_00', '_merge_without_sq_00', '_merge_00', 'Cartilage_Morphology_03', 'Partial_TCL_03', 'Full_TCL_03', 'BML_03', 'Meniscus_Degradation_03', 'VERSION_03', 'READPRJ_03', 'V03MWMTMA_03', 'V03MWMTMB_03', 'V03MWMTMP_03', 'V03MWMTLA_03', 'V03MWMTLB_03', 'V03MWMTLP_03', 'V03MWMTMS_03', 'V03MWMTLS_03', 'V03MWACL_03', 'V03MWPCL_03', 'V03MWMCL_03', 'V03MWLCL_03', 'V03MWPATND_03', 'V03MWPOTND_03', 'V03MWCMP_03', 'V03MWCMFT_03', 'V03MWCMFM_03', 'V03MWCMFL_03', 'V03MWCMTM_03', 'V03MWCMTL_03', 'V03MWBMP_03', 'V03MWBMFT_03', 'V03MWBMFM_03', 'V03MWBMFL_03', 'V03MWBMTM_03', 'V03MWBMTL_03', 'V03MWEFFWK_03', 'V03MWLB_03', 'V03MWPOPCY_03', '_merge_without_sq_03', '_merge_03', 'Cartilage_Morphology_06', 'BML_06', 'Meniscus_Degradation_06', 'VERSION_06', 'READPRJ_06', 'V06MWMTMA_06', 'V06MWMTMB_06', 'V06MWMTMP_06', 'V06MWMTLA_06', 'V06MWMTLB_06', 'V06MWMTLP_06', 'V06MWMTMS_06', 'V06MWMTLS_06', 'V06MWACL_06', 'V06MWPCL_06', 'V06MWMCL_06', 'V06MWLCL_06', 'V06MWPATND_06', 'V06MWPOTND_06', 'V06MWCMP_06', 'V06MWCMFT_06', 'V06MWCMFM_06', 'V06MWCMFL_06', 'V06MWCMTM_06', 'V06MWCMTL_06', 'V06MWBMP_06', 'V06MWBMFT_06', 'V06MWBMFM_06', 'V06MWBMFL_06', 'V06MWBMTM_06', 'V06MWBMTL_06', 'V06MWEFFWK_06', 'V06MWLB_06', 'V06MWPOPCY_06', '_merge_without_fnih_06']

In [9]:
all_subjects_in_all_follow_ups.fillna(-1.0,inplace=True)
all_subjects_in_all_follow_ups.to_csv('all_subjects_worms_sq00_03_06.csv')

# FIRST WE FIND THE SUBJECTS THAT REMAINED ZERO IN EACH TIME-STEP
# FOR EACH FEATURE SEPARATELY

In [10]:
all_worms_cart_zero_sq00_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.Cartilage_Morphology_00 == 0) &   
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_03 == 0)),
                        ['ID','SIDE','Cartilage_Morphology_00','Cartilage_Morphology_03']]
all_worms_cart_zero_sq00_03_06 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.Cartilage_Morphology_00 == 0) &  
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_03 == 0) & 
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_06 == 0)),
                        ['ID','SIDE','Cartilage_Morphology_00','Cartilage_Morphology_03','Cartilage_Morphology_06']]

print('Number of subject that remained ZERO Cartilage in SQ00 and SQ03: {}'.format(all_worms_cart_zero_sq00_03.shape[0]))
print('Number of subject that remained ZERO Cartilage in SQ00 and SQ03 and SQ06: {}'.format(all_worms_cart_zero_sq00_03_06.shape[0]))

all_worms_cart_zero_sq00_03.to_csv('worms_sq00_03_Cartilage_that_remains_zero_thres1.csv')
all_worms_cart_zero_sq00_03_06.to_csv('worms_sq00_03_06_Cartilage_that_remains_zero_thres1.csv')

Number of subject that remained ZERO Cartilage in SQ00 and SQ03: 129
Number of subject that remained ZERO Cartilage in SQ00 and SQ03 and SQ06: 81

In [11]:
all_worms_bml_zero_sq00_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.BML_00 == 0) & 
                        (all_subjects_in_all_follow_ups.BML_03 == 0)),
                        ['ID','SIDE','BML_00','BML_03']]
all_worms_bml_zero_sq00_03_06 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.BML_00 == 0) &
                        (all_subjects_in_all_follow_ups.BML_03 == 0)&
                        (all_subjects_in_all_follow_ups.BML_06 == 0)),
                        ['ID','SIDE','BML_00','BML_03','BML_06']]

print('Number of subject that remained ZERO BML in SQ00 and SQ03: {}'.format(all_worms_bml_zero_sq00_03.shape[0]))
print('Number of subject that remained ZERO BML in SQ00 and SQ03 and SQ06: {}'.format(all_worms_bml_zero_sq00_03_06.shape[0]))

all_worms_bml_zero_sq00_03.to_csv('worms_sq00_03_BML_that_remain_zero_thres1.csv')
all_worms_bml_zero_sq00_03_06.to_csv('worms_sq00_03_06_BML_that_remain_zero_thres1.csv')

Number of subject that remained ZERO BML in SQ00 and SQ03: 185
Number of subject that remained ZERO BML in SQ00 and SQ03 and SQ06: 175

In [12]:
all_worms_men_zero_sq00_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.Meniscus_Degradation_00 == 0) & 
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_03 == 0)),
                        ['ID','SIDE','Meniscus_Degradation_00','Meniscus_Degradation_03']]
all_worms_men_zero_sq00_03_06 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.Meniscus_Degradation_00 == 0) & 
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_03 == 0) &
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_06 == 0)),
                        ['ID','SIDE','Meniscus_Degradation_00','Meniscus_Degradation_03','Meniscus_Degradation_06']]

print('Number of subject that remained ZERO Meniscual Degradation in SQ00 and SQ03: {}'.format(all_worms_men_zero_sq00_03.shape[0]))
print('Number of subject that remained ZERO Meniscual Degradation in SQ00 and SQ03 and SQ06: {}'.format(all_worms_men_zero_sq00_03_06.shape[0]))

all_worms_men_zero_sq00_03.to_csv('worms_sq00_03_Meniscus_that_remain_zero_thres1.csv')
all_worms_men_zero_sq00_03_06.to_csv('worms_sq00_03_06_Meniscus_that_remain_zero_thres1.csv')

Number of subject that remained ZERO Meniscual Degradation in SQ00 and SQ03: 114
Number of subject that remained ZERO Meniscual Degradation in SQ00 and SQ03 and SQ06: 99

# NOW WE FIND THE NUMBER OF SUBJECTS THAT PROGRESSED FROM EACH TIME-STEP
# FOR EACH FEATURE

In [13]:
all_worms_zero_sq00_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.BML_00 == 0) & 
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_00 == 0) & 
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_00 == 0) & 
                        (all_subjects_in_all_follow_ups.BML_03 == 1) & 
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_03 == 1) & 
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_03 == 1)),
                        ['ID','SIDE','Cartilage_Morphology_00','BML_00','Meniscus_Degradation_00',
                        'Cartilage_Morphology_03','BML_03','Meniscus_Degradation_03']]
all_worms_zero_sq00_03_one_06 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.BML_00 == 0) & 
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_00 == 0) & 
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_00 == 0) & 
                        (all_subjects_in_all_follow_ups.BML_03 == 0) & 
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_03 == 0) & 
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_03 == 0) &
                        (all_subjects_in_all_follow_ups.BML_06 == 1) & 
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_06 == 1) & 
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_06 == 1)),
                        ['ID','SIDE','Cartilage_Morphology_00','BML_00','Meniscus_Degradation_00',
                        'Cartilage_Morphology_03','BML_03','Meniscus_Degradation_03',
                        'Cartilage_Morphology_06','BML_06','Meniscus_Degradation_06']]

print('Number of subject that remained ZERO WORMS in SQ00 and PROGRESSED TO ONE in SQ03: {}'.format(all_worms_zero_sq00_one_03.shape[0]))
print('Number of subject that remained ZERO WORMS in SQ00 and SQ03 and PROGRESSED TO ONE in SQ06: {}'.format(all_worms_zero_sq00_03_one_06.shape[0]))

Number of subject that remained ZERO WORMS in SQ00 and PROGRESSED TO ONE in SQ03: 2
Number of subject that remained ZERO WORMS in SQ00 and SQ03 and PROGRESSED TO ONE in SQ06: 1

In [14]:
all_worms_BML_zero_sq00_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.BML_00 == 0) & 
                        (all_subjects_in_all_follow_ups.BML_03 == 1)),
                        ['ID','SIDE','Cartilage_Morphology_00','BML_00','Meniscus_Degradation_00',
                        'Cartilage_Morphology_03','BML_03','Meniscus_Degradation_03']]
all_worms_BML_zero_sq00_03_one_06 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.BML_00 == 0) &  
                        (all_subjects_in_all_follow_ups.BML_03 == 0) & 
                        (all_subjects_in_all_follow_ups.BML_06 == 1) ),
                        ['ID','SIDE','Cartilage_Morphology_00','BML_00','Meniscus_Degradation_00',
                        'Cartilage_Morphology_03','BML_03','Meniscus_Degradation_03',
                        'Cartilage_Morphology_06','BML_06','Meniscus_Degradation_06']]
print('Number of subject that remained ZERO BML WORMS in SQ00 and PROGRESSED TO ONE in SQ03: {}'.format(all_worms_BML_zero_sq00_one_03.shape[0]))
print('Number of subject that remained ZERO BML WORMS in SQ00 and SQ03 and PROGRESSED TO ONE in SQ06: {}'.format(all_worms_BML_zero_sq00_03_one_06.shape[0]))
all_worms_BML_zero_sq00_one_03.to_csv('worms_sq00_03_BML_progression_thres1.csv')
all_worms_BML_zero_sq00_03_one_06.to_csv('worms_sq00_03_06_BML_progression_thres1.csv')

Number of subject that remained ZERO BML WORMS in SQ00 and PROGRESSED TO ONE in SQ03: 11
Number of subject that remained ZERO BML WORMS in SQ00 and SQ03 and PROGRESSED TO ONE in SQ06: 10

In [15]:
all_worms_Cart_zero_sq00_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.Cartilage_Morphology_00 == 0) & 
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_00 == 1)),
                        ['ID','SIDE','Cartilage_Morphology_00','BML_00','Meniscus_Degradation_00',
                        'Cartilage_Morphology_03','BML_03','Meniscus_Degradation_03']]
all_worms_Cart_zero_sq00_03_one_06 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.Cartilage_Morphology_00 == 0) &  
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_03 == 0) & 
                        (all_subjects_in_all_follow_ups.Cartilage_Morphology_06 == 1) ),
                        ['ID','SIDE','Cartilage_Morphology_00','BML_00','Meniscus_Degradation_00',
                        'Cartilage_Morphology_03','BML_03','Meniscus_Degradation_03',
                        'Cartilage_Morphology_06','BML_06','Meniscus_Degradation_06']]
print('Number of subject that remained ZERO Cartilage WORMS in SQ00 and PROGRESSED TO ONE in SQ03: {}'.format(all_worms_Cart_zero_sq00_one_03.shape[0]))
print('Number of subject that remained ZERO Cartilage WORMS in SQ00 and SQ03 and PROGRESSED TO ONE in SQ06: {}'.format(all_worms_Cart_zero_sq00_03_one_06.shape[0]))
all_worms_Cart_zero_sq00_one_03.to_csv('worms_sq00_03_Cartilage_progression_thres1.csv')
all_worms_Cart_zero_sq00_03_one_06.to_csv('worms_sq00_03_06_Cartilage_progression_thres1.csv')

Number of subject that remained ZERO Cartilage WORMS in SQ00 and PROGRESSED TO ONE in SQ03: 0
Number of subject that remained ZERO Cartilage WORMS in SQ00 and SQ03 and PROGRESSED TO ONE in SQ06: 48

In [16]:
all_worms_Men_zero_sq00_one_03 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.Meniscus_Degradation_00 == 0) & 
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_03 == 1)),
                        ['ID','SIDE','Cartilage_Morphology_00','BML_00','Meniscus_Degradation_00',
                        'Cartilage_Morphology_03','BML_03','Meniscus_Degradation_03']]
all_worms_Men_zero_sq00_03_one_06 = all_subjects_in_all_follow_ups.loc[((all_subjects_in_all_follow_ups.Meniscus_Degradation_00 == 0) &  
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_03 == 0) & 
                        (all_subjects_in_all_follow_ups.Meniscus_Degradation_06 == 1) ),
                        ['ID','SIDE','Cartilage_Morphology_00','BML_00','Meniscus_Degradation_00',
                        'Cartilage_Morphology_03','BML_03','Meniscus_Degradation_03',
                        'Cartilage_Morphology_06','BML_06','Meniscus_Degradation_06']]
print('Number of subject that remained ZERO MEniscus Degradation WORMS in SQ00 and PROGRESSED TO ONE in SQ03: {}'.format(all_worms_Men_zero_sq00_one_03.shape[0]))
print('Number of subject that remained ZERO MEniscus Degradation WORMS in SQ00 and SQ03 and PROGRESSED TO ONE in SQ06: {}'.format(all_worms_Men_zero_sq00_03_one_06.shape[0]))
all_worms_Men_zero_sq00_one_03.to_csv('worms_sq00_03_Meniscus_progression_thres1.csv')
all_worms_Men_zero_sq00_03_one_06.to_csv('worms_sq00_03_06_Meniscus_progression_thres1.csv')

Number of subject that remained ZERO MEniscus Degradation WORMS in SQ00 and PROGRESSED TO ONE in SQ03: 47
Number of subject that remained ZERO MEniscus Degradation WORMS in SQ00 and SQ03 and PROGRESSED TO ONE in SQ06: 15

# MOAKS THAT REMAINED ZERO BETWEEN 00 AND 03

In [17]:
worms_OA_criteria_thres1_00 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/WORMS/SQ_Link00/worms_OA_criteria_thres1.csv',index_col=0)
worms_OA_criteria_thres1_03 = pd.read_csv('/home/anastasis/EMC_Thesis/My_codes/WORMS/SQ_Link03/worms_OA_criteria_thres1.csv',index_col=0)
all_worms_OA_criteria_thres1 = pd.merge(worms_OA_criteria_thres1_00,worms_OA_criteria_thres1_03,on=['ID','SIDE'],how='inner')
all_worms_OA_criteria_thres1.rename(columns=lambda x: x.replace('_x','_00'),inplace=True)
all_worms_OA_criteria_thres1.rename(columns=lambda x: x.replace('_y','_03'),inplace=True)
all_worms_OA_criteria_thres1

,ID,SIDE,Osteo_AND_Full_TCL_00,Osteo_AND_Partial_TCL_AND_BML_00,Osteo_AND_Partial_TCL_AND_Meniscus_Degradation_00,Osteo_AND_BML_AND_Meniscus_Degradation_00,Full_TCL_AND_BML_AND_Meniscus_Degradation_00,moaks_OA_00,Osteo_AND_Full_TCL_03,Osteo_AND_Partial_TCL_AND_BML_03,Osteo_AND_Partial_TCL_AND_Meniscus_Degradation_03,Osteo_AND_BML_AND_Meniscus_Degradation_03,Full_TCL_AND_BML_AND_Meniscus_Degradation_03,moaks_OA_03
0,9057417,1,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0
1,9061827,1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
2,9064631,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9065433,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,9098924,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,9901658,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57,9928863,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,9939547,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59,9946897,1,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
60,9969009,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
worms_OA_thres1_zero00_one03 = all_worms_OA_criteria_thres1.loc[(
    (all_worms_OA_criteria_thres1.moaks_OA_00 == 0) & (all_worms_OA_criteria_thres1.moaks_OA_03 == 1)),
    ['ID','SIDE','moaks_OA_00','moaks_OA_03']]
worms_OA_thres1_zero00_one03.to_csv('worms_OA_thres1_zero00_one03.csv')
worms_OA_thres1_zero00_one03.shape[0]

4

In [19]:
worms_OA_thres1_zero0003 = all_worms_OA_criteria_thres1.loc[(
    (all_worms_OA_criteria_thres1.moaks_OA_00 == 0) & (all_worms_OA_criteria_thres1.moaks_OA_03 == 0)),
    ['ID','SIDE','moaks_OA_00','moaks_OA_03']]
worms_OA_thres1_zero0003.to_csv('worms_OA_thres1_zero0003.csv')
worms_OA_thres1_zero0003.shape[0]

43